(()=>{'use strict';
const P=globalThis.MundoMimoV2,E=globalThis.MundoMimoV2ExpansionV300;if(!P||!E)throw new Error('Mundo Mimo V2 v310 catalog dependencies missing');
const G=(id,name,ages,area,skill,subskill,mechanic,objective,interaction,win,progression)=>Object.freeze({id,name,ages,area,skill,subskill,mechanic,objective,rules:Object.freeze({interaction,win,progression}),levels:12,feedback:Object.freeze({correct:'descriptivo-breve',incorrect:'pista-gradual'}),hints:Object.freeze(['modelado','reduccion-distractores','repeticion-posterior']),accessibility:Object.freeze(['visual','audio','touch','reduced-motion'])});
const GAMES=Object.freeze([
G('caras-y-gestos','Caras y gestos',['1-2','2-3'],'emociones','imitacion-emocional','gestos-faciales','gesture-match','Reconocer expresiones emocionales básicas asociando una cara con una situación sencilla.','observar una situación y tocar la expresión facial que mejor encaja','elegir la emoción coherente con la situación','ampliar de alegría/tristeza a sorpresa, enfado y calma con contextos menos evidentes'),
G('cuenta-y-reparte','Cuenta y reparte',['3-4','4-5'],'matematicas','correspondencia-uno-a-uno','reparto-equitativo','one-to-one-distribute','Practicar conteo y correspondencia uno a uno repartiendo objetos entre personajes.','tocar personajes para repartir exactamente un objeto a cada uno hasta agotar la cantidad','completar el reparto sin dejar personajes vacíos ni entregar de más','aumentar receptores y comparar repartos iguales y desiguales'),
G('sonido-intruso','El sonido intruso',['4-5','5-6'],'conciencia-fonologica','discriminacion-auditiva','sonido-inicial','phoneme-odd-one-out','Detectar qué palabra comienza por un sonido diferente dentro de un pequeño grupo.','escuchar o leer apoyos visuales de tres palabras y elegir la que empieza diferente','identificar el elemento con sonido inicial distinto','usar contrastes fonológicos progresivamente más próximos'),
G('mapa-de-mi-casa','Mapa de mi casa',['3-4','4-5'],'orientacion-espacial','relaciones-espaciales','delante-detras-encima-debajo','spatial-place','Comprender relaciones espaciales colocando objetos respecto a referencias familiares.','elegir la posición que cumple una instrucción espacial breve','situar el objeto en la relación espacial solicitada','combinar dos relaciones y reducir apoyos visuales'),
G('historia-con-emociones','Historia con emociones',['4-5','5-6'],'lenguaje','comprension-narrativa','emocion-y-causa','story-emotion-chain','Relacionar acontecimientos de una historia breve con cambios emocionales del personaje.','leer o escuchar tres escenas y elegir la emoción coherente después de cada acontecimiento','completar correctamente la cadena acontecimiento-emoción','incorporar emociones mixtas y pedir anticipar cómo puede sentirse después'),
G('mini-mercado','Mini mercado',['5-6'],'matematicas','composicion-de-cantidades','suma-con-monedas','coin-composition','Componer cantidades pequeñas usando monedas simbólicas sin introducir dinero real ni compra comercial.','seleccionar fichas de valor 1, 2 o 3 hasta alcanzar exactamente el precio objetivo','igualar la cantidad objetivo sin sobrepasarla','aumentar objetivo y buscar más de una combinación válida')
]);
const merged=[...E.merged,...GAMES],errors=P.validateCatalog(GAMES),clones=P.cloneGroups(merged);
if(errors.length)console.error('Mundo Mimo V2 v310 catalog errors',errors);if(clones.length)console.error('Mundo Mimo V2 v310 clone groups',clones);
globalThis.MundoMimoV2ExpansionV310=Object.freeze({version:310,games:GAMES,errors,cloneGroups:clones,merged:Object.freeze(merged)});
})();