(()=>{'use strict';
const P=globalThis.MundoMimoV2,E=globalThis.MundoMimoV2ExpansionV270;if(!P||!E)throw new Error('Mundo Mimo V2 v280 catalog dependencies missing');
const G=(id,name,ages,area,skill,subskill,mechanic,objective,interaction,win,progression)=>Object.freeze({id,name,ages,area,skill,subskill,mechanic,objective,rules:Object.freeze({interaction,win,progression}),levels:12,feedback:Object.freeze({correct:'descriptivo-breve',incorrect:'pista-gradual'}),hints:Object.freeze(['modelado','reduccion-distractores','repeticion-posterior']),accessibility:Object.freeze(['visual','audio','touch','reduced-motion'])});
const GAMES=Object.freeze([
G('sonidos-del-cuerpo','Sonidos del cuerpo',['1-2','2-3'],'lenguaje','conciencia-corporal','accion-sonido','tap-target','Relacionar acciones corporales cotidianas con el sonido o efecto que producen.','observar una acción y tocar la parte u opción corporal correspondiente','seleccionar la acción corporal que explica la pista','añadir acciones próximas y secuencias de dos pistas'),
G('mitades-que-encajan','Mitades que encajan',['2-3','3-4'],'prelectura','percepcion-parte-todo','completar-imagen','pair-match','Reconstruir objetos familiares uniendo dos mitades visualmente complementarias.','seleccionar una mitad y después su complemento correcto','completar todas las parejas de mitades','más parejas, rotación visual y siluetas menos evidentes'),
G('ruta-de-formas','Ruta de formas',['3-4','4-5'],'geometria','orientacion-espacial','ruta-por-propiedad','spatial-navigation','Seguir una ruta atendiendo a una regla geométrica cambiante.','avanzar por casillas eligiendo únicamente formas que cumplen la regla','alcanzar la meta sin pisar una forma prohibida','combinar forma, color y posición en reglas sucesivas'),
G('ordena-la-receta','Ordena la receta',['4-5','5-6'],'autonomia','planificacion-cotidiana','secuencia-de-preparacion','step-order','Ordenar pasos funcionales de una preparación cotidiana sencilla.','reordenar tarjetas de acciones hasta formar una secuencia segura y lógica','todos los pasos quedan en orden causal','añadir pasos opcionales y distractores plausibles'),
G('jardin-de-estaciones','Jardín de estaciones',['4-5','5-6'],'ciencia','ciclos-naturales','estaciones-y-plantas','simple-simulation','Relacionar condiciones estacionales con cambios observables en plantas y entorno.','elegir una estación y comprobar su efecto en una escena de jardín','predecir correctamente el cambio principal antes de simularlo','añadir clima, temperatura y varias consecuencias simultáneas'),
G('detective-de-silabas','Detective de sílabas',['5-6'],'conciencia-fonologica','segmentacion-silabica','numero-de-silabas','multi-select','Identificar palabras que comparten el mismo número de sílabas mediante segmentación oral apoyada.','escuchar o leer una palabra modelo y seleccionar todas las imágenes con igual número de golpes silábicos','seleccionar exactamente el conjunto con la misma estructura silábica','pasar de palabras bisílabas a mezclas de dos, tres y cuatro sílabas')
]);
const merged=[...E.merged,...GAMES],errors=P.validateCatalog(GAMES),clones=P.cloneGroups(merged);
if(errors.length)console.error('Mundo Mimo V2 v280 catalog errors',errors);if(clones.length)console.error('Mundo Mimo V2 v280 clone groups',clones);
globalThis.MundoMimoV2ExpansionV280=Object.freeze({version:280,games:GAMES,errors,cloneGroups:clones,merged:Object.freeze(merged)});
})();