(()=>{'use strict';
const P=globalThis.MundoMimoV2,E=globalThis.MundoMimoV2ExpansionV290;if(!P||!E)throw new Error('Mundo Mimo V2 v300 catalog dependencies missing');
const G=(id,name,ages,area,skill,subskill,mechanic,objective,interaction,win,progression)=>Object.freeze({id,name,ages,area,skill,subskill,mechanic,objective,rules:Object.freeze({interaction,win,progression}),levels:12,feedback:Object.freeze({correct:'descriptivo-breve',incorrect:'pista-gradual'}),hints:Object.freeze(['modelado','reduccion-distractores','repeticion-posterior']),accessibility:Object.freeze(['visual','audio','touch','reduced-motion'])});
const GAMES=Object.freeze([
G('animales-dia-noche','Animales de día y de noche',['3-4','4-5'],'ciencia','clasificacion-biologica','ritmos-de-actividad','category-sort','Distinguir de forma introductoria animales habitualmente activos de día o de noche sin presentar la regla como absoluta.','clasificar tarjetas de animales en escenas de día o noche según el ejemplo aprendido','clasificar correctamente el conjunto de la ronda','introducir especies menos familiares y recordar que algunos patrones pueden variar'),
G('ropa-para-el-tiempo','¿Qué me pongo?',['2-3','3-4'],'autonomia','eleccion-de-ropa','clima-y-vestido','context-choice','Elegir prendas funcionales según situaciones meteorológicas cotidianas.','observar una escena de clima y elegir la prenda más útil entre opciones familiares','seleccionar una prenda adecuada al contexto mostrado','pasar de contrastes evidentes a combinar dos pistas como lluvia y temperatura'),
G('palmas-y-silencios','Palmas y silencios',['3-4','4-5'],'musica','ritmo','pulso-y-silencio','sequence-imitate','Reconocer que el silencio también forma parte de una secuencia rítmica y reproducir patrones breves.','observar una secuencia de palma y silencio y reproducirla con dos controles diferenciados','repetir el patrón completo respetando posición de sonidos y silencios','aumentar longitud e introducir dobles palmas manteniendo tempo lento'),
G('letra-escondida','La letra escondida',['4-5','5-6'],'prelectura','discriminacion-alfabetica','letra-en-escena','hidden-object','Localizar una grafía objetivo integrada entre símbolos visualmente parecidos.','buscar y tocar todas las apariciones de una letra objetivo dentro de una escena de símbolos','encontrar todas las grafías objetivo sin seleccionar distractores','reducir diferencias visuales y alternar mayúsculas y minúsculas'),
G('turnos-en-el-parque','Turnos en el parque',['3-4','4-5'],'habilidades-sociales','turnos','espera-y-acuerdo','consequence-choice','Explorar respuestas prosociales cuando dos niños quieren usar el mismo recurso al mismo tiempo.','observar una situación breve y elegir una acción que respete turnos o acuerdos','elegir una alternativa segura y prosocial entre varias consecuencias','incorporar acuerdos, pedir turno y soluciones cooperativas diversas'),
G('puente-de-formas','Puente de formas',['4-5','5-6'],'geometria','construccion-espacial','soporte-y-longitud','block-build','Planificar una construcción sencilla que conecte dos apoyos usando piezas de longitudes diferentes.','seleccionar y colocar piezas geométricas para cubrir una distancia objetivo sin sobrepasarla','completar exactamente la longitud del puente con una combinación válida','aumentar distancia, limitar piezas disponibles y pedir más de una solución posible')
]);
const merged=[...E.merged,...GAMES],errors=P.validateCatalog(GAMES),clones=P.cloneGroups(merged);
if(errors.length)console.error('Mundo Mimo V2 v300 catalog errors',errors);if(clones.length)console.error('Mundo Mimo V2 v300 clone groups',clones);
globalThis.MundoMimoV2ExpansionV300=Object.freeze({version:300,games:GAMES,errors,cloneGroups:clones,merged:Object.freeze(merged)});
})();