(()=>{'use strict';
const P=globalThis.MundoMimoV2,E=globalThis.MundoMimoV2ExpansionV390;if(!P||!E)throw new Error('Mundo Mimo V2 v400 catalog dependencies missing');
const G=(id,name,ages,area,skill,subskill,mechanic,objective,interaction,win,progression)=>Object.freeze({id,name,ages,area,skill,subskill,mechanic,objective,rules:Object.freeze({interaction,win,progression}),levels:12,feedback:Object.freeze({correct:'descriptivo-breve',incorrect:'pista-gradual'}),hints:Object.freeze(['modelado','reduccion-distractores','repeticion-posterior']),accessibility:Object.freeze(['visual','audio','touch','reduced-motion'])});
const GAMES=Object.freeze([
G('encuentra-mi-casa','Encuentra mi casa',['1-2','2-3'],'mundo-cotidiano','lugares-y-funciones','objeto-y-lugar','spatial-place','Relacionar objetos cotidianos con el lugar habitual donde se usan o guardan.','observar un objeto y colocarlo en uno de varios lugares familiares','elegir el lugar coherente con la función del objeto','pasar de dos a cuatro lugares y añadir distractores funcionalmente próximos'),
G('semaforo-de-turnos','Semáforo de turnos',['2-3','3-4'],'habilidades-sociales','espera-y-turno','inhibicion-social','age-safe-reaction','Practicar esperar una señal clara antes de actuar en una situación social sencilla.','esperar a que el indicador cambie a verde antes de tocar el personaje','actuar solo cuando aparece la señal de turno','reducir apoyos visuales y alternar tiempos de espera cortos y medios'),
G('que-cambio','¿Qué cambió?',['3-4','4-5'],'atencion','cambio-visual','comparacion-escenas','spot-difference','Detectar un cambio relevante entre dos escenas simples manteniendo la atención visual.','observar una escena inicial y después señalar el elemento que cambió','identificar el único cambio objetivo','aumentar de tres a seis elementos y usar cambios de posición o atributo'),
G('pasos-y-palabras','Pasos y palabras',['3-4','4-5'],'psicomotricidad','secuencia-motora','accion-y-orden','multi-instruction','Seguir una secuencia breve de acciones motoras asociadas a palabras conocidas.','escuchar o leer dos o tres acciones y tocarlas en el orden indicado','reproducir toda la secuencia sin alterar el orden','progresar de dos a cuatro pasos e introducir acciones parecidas'),
G('elige-la-pista','Elige la pista',['4-5','5-6'],'logica','deduccion-por-pistas','descartar-opciones','logic-grid','Resolver una selección lógica sencilla usando dos pistas explícitas.','leer dos pistas y descartar candidatos hasta dejar una sola opción válida','elegir el candidato que satisface simultáneamente ambas pistas','añadir una tercera pista y distractores que cumplen solo parte de las condiciones'),
G('inventa-el-final','Inventa el final',['5-6'],'creatividad','narracion-creativa','final-coherente','interactive-story','Elegir y justificar un final coherente para una historia breve abierta.','leer una situación y seleccionar entre finales posibles antes de explicar la elección','escoger un desenlace compatible con los hechos previos y la emoción del personaje','pasar de finales muy contrastados a opciones plausibles con matices')
]);
const merged=[...E.merged,...GAMES],errors=P.validateCatalog(GAMES),clones=P.cloneGroups(merged);
if(errors.length)console.error('Mundo Mimo V2 v400 catalog errors',errors);if(clones.length)console.error('Mundo Mimo V2 v400 clone groups',clones);
globalThis.MundoMimoV2ExpansionV400=Object.freeze({version:400,games:GAMES,errors,cloneGroups:clones,merged:Object.freeze(merged)});
})();