(()=>{'use strict';
const P=globalThis.MundoMimoV2,E=globalThis.MundoMimoV2ExpansionV420;if(!P||!E)throw new Error('Mundo Mimo V2 v430 catalog dependencies missing');
const G=(id,name,ages,area,skill,subskill,mechanic,objective,interaction,win,progression)=>Object.freeze({id,name,ages,area,skill,subskill,mechanic,objective,rules:Object.freeze({interaction,win,progression}),levels:12,feedback:Object.freeze({correct:'descriptivo-breve',incorrect:'pista-gradual'}),hints:Object.freeze(['modelado','reduccion-distractores','repeticion-posterior']),accessibility:Object.freeze(['visual','audio','touch','reduced-motion'])});
const GAMES=Object.freeze([
G('eco-de-gestos','Eco de gestos',['0-1','1-2'],'psicomotricidad','imitacion-motora','gestos-sencillos','gesture-match','Favorecer imitación motora y atención conjunta mediante gestos corporales sencillos.','observar un gesto representado y tocar la tarjeta que muestra la misma acción','elegir el gesto que reproduce el modelo','pasar de dos opciones muy distintas a tres gestos más parecidos'),
G('caja-de-sonidos','Caja de sonidos',['1-2','2-3'],'lenguaje','vocabulario-auditivo','objeto-y-sonido','listen-choose','Relacionar sonidos cotidianos con objetos familiares para reforzar comprensión auditiva.','escuchar una pista sonora representada y elegir el objeto que normalmente la produce','seleccionar el objeto asociado al sonido objetivo','aumentar de dos a tres distractores y usar sonidos funcionalmente próximos'),
G('torres-iguales','Torres iguales',['2-3','3-4'],'matematicas','equivalencia-inicial','misma-cantidad','geometry-build','Comprender igualdad de cantidades construyendo dos colecciones equivalentes.','añadir bloques a una segunda torre hasta que tenga la misma cantidad que el modelo','igualar exactamente el número de bloques de ambas torres','progresar de cantidades 2-3 a 5-6 y retirar parte del apoyo visual'),
G('palabra-y-dibujo','Palabra y dibujo',['3-4','4-5'],'prelectura','asociacion-palabra-imagen','reconocimiento-global','visual-recognition','Relacionar palabras familiares de alta frecuencia con su representación visual.','leer o escuchar una palabra breve y elegir entre dibujos el que corresponde','seleccionar la imagen que representa la palabra objetivo','pasar de vocabulario muy familiar a palabras visualmente o semánticamente próximas'),
G('camino-con-reglas','Camino con reglas',['4-5','5-6'],'funciones-ejecutivas','planificacion-con-reglas','inhibicion-y-cambio','spatial-navigation','Planificar un recorrido respetando simultáneamente una meta y una regla de paso.','elegir sucesivamente casillas permitidas evitando la señal prohibida hasta llegar a la meta','alcanzar la meta sin pisar ninguna casilla vetada','introducir dos reglas simultáneas y recorridos más largos'),
G('detective-de-causas','Detective de causas',['5-6'],'ciencia','razonamiento-causal','causa-y-evidencia','problem-solve','Inferir la causa más probable de un resultado cotidiano usando evidencias observables.','leer una situación breve y escoger la explicación compatible con todas las pistas','seleccionar la causa que explica el resultado sin contradecir la evidencia','pasar de una pista explícita a dos indicios que requieren descartar explicaciones plausibles')
]);
const merged=[...E.merged,...GAMES],errors=P.validateCatalog(GAMES),clones=P.cloneGroups(merged);
if(errors.length)console.error('Mundo Mimo V2 v430 catalog errors',errors);if(clones.length)console.error('Mundo Mimo V2 v430 clone groups',clones);
globalThis.MundoMimoV2ExpansionV430=Object.freeze({version:430,games:GAMES,errors,cloneGroups:clones,merged:Object.freeze(merged)});
})();