(()=>{'use strict';
const P=globalThis.MundoMimoV2,E=globalThis.MundoMimoV2ExpansionV320;if(!P||!E)throw new Error('Mundo Mimo V2 v330 catalog dependencies missing');
const G=(id,name,ages,area,skill,subskill,mechanic,objective,interaction,win,progression)=>Object.freeze({id,name,ages,area,skill,subskill,mechanic,objective,rules:Object.freeze({interaction,win,progression}),levels:12,feedback:Object.freeze({correct:'descriptivo-breve',incorrect:'pista-gradual'}),hints:Object.freeze(['modelado','reduccion-distractores','repeticion-posterior']),accessibility:Object.freeze(['visual','audio','touch','reduced-motion'])});
const GAMES=Object.freeze([
G('imita-la-cara','Imita la cara',['1-2','2-3'],'emociones','imitacion-emocional','gesto-y-expresion','visual-recognition','Reconocer expresiones faciales muy básicas y relacionarlas con una imitación sencilla.','observar la expresión del personaje y elegir la cara que reproduce el mismo gesto','seleccionar la expresión visual equivalente','pasar de dos a cuatro expresiones con menor exageración visual'),
G('donde-esta-mimo','¿Dónde está Mimo?',['2-3','3-4'],'lenguaje','conceptos-espaciales','encima-debajo-dentro-fuera','context-choice','Comprender vocabulario espacial básico usando escenas concretas y familiares.','observar una escena y elegir la palabra espacial que describe la posición de Mimo','identificar correctamente la relación espacial mostrada','incorporar delante/detrás y relaciones entre dos objetos'),
G('mision-de-movimientos','Misión de movimientos',['3-4','4-5'],'funciones-ejecutivas','memoria-de-trabajo','secuencia-de-acciones','multi-instruction','Retener y ejecutar en orden dos o más instrucciones visuales breves.','observar una secuencia de acciones y pulsar sus símbolos en el mismo orden','reproducir la secuencia completa sin alterar el orden','aumentar de dos a cuatro pasos e introducir distractores'),
G('empiezan-igual','Empiezan igual',['4-5','5-6'],'conciencia-fonologica','sonido-inicial','grupo-de-palabras','multi-select','Identificar varias palabras que comparten el mismo sonido inicial.','escuchar o ver un sonido inicial y seleccionar todas las imágenes que empiezan por él','marcar exactamente el conjunto de palabras con el sonido objetivo','usar fonemas próximos y retirar gradualmente apoyo escrito'),
G('haz-diez','Haz diez',['5-6'],'matematicas','composicion-de-cantidades','parejas-que-suman-diez','problem-solve','Descomponer el número diez en dos cantidades y reconocer distintas combinaciones equivalentes.','elegir una pareja de tarjetas numéricas cuya suma sea diez','formar exactamente diez con dos cantidades','alternar objetivos de cinco a diez y pedir más de una descomposición válida'),
G('laboratorio-de-mezclas','Laboratorio de mezclas',['3-4','4-5','5-6'],'ciencia','prediccion-y-comprobacion','mezcla-de-colores','simple-simulation','Predecir y comprobar el resultado de mezclar colores primarios mediante una simulación visual sencilla.','observar dos colores, predecir el resultado y activar la mezcla para comprobarlo','elegir el color resultante correcto y verificar la simulación','incorporar más combinaciones y pedir predicción antes de mostrar opciones')
]);
const merged=[...E.merged,...GAMES],errors=P.validateCatalog(GAMES),clones=P.cloneGroups(merged);
if(errors.length)console.error('Mundo Mimo V2 v330 catalog errors',errors);if(clones.length)console.error('Mundo Mimo V2 v330 clone groups',clones);
globalThis.MundoMimoV2ExpansionV330=Object.freeze({version:330,games:GAMES,errors,cloneGroups:clones,merged:Object.freeze(merged)});
})();