(()=>{'use strict';
const P=globalThis.MundoMimoV2,E=globalThis.MundoMimoV2ExpansionV350;if(!P||!E)throw new Error('Mundo Mimo V2 v360 catalog dependencies missing');
const G=(id,name,ages,area,skill,subskill,mechanic,objective,interaction,win,progression)=>Object.freeze({id,name,ages,area,skill,subskill,mechanic,objective,rules:Object.freeze({interaction,win,progression}),levels:12,feedback:Object.freeze({correct:'descriptivo-breve',incorrect:'pista-gradual'}),hints:Object.freeze(['modelado','reduccion-distractores','repeticion-posterior']),accessibility:Object.freeze(['visual','audio','touch','reduced-motion'])});
const GAMES=Object.freeze([
G('busca-la-pareja-de-sombras','Busca la pareja de sombras',['2-3','3-4','4-5'],'atencion','discriminacion-visual','objeto-y-silueta','pair-match','Relacionar cada objeto con su silueta atendiendo a contorno y proporción.','observar un objeto y escoger entre varias siluetas visualmente próximas','seleccionar la silueta que corresponde al objeto modelo','reducir diferencias de contorno y añadir rotaciones sencillas'),
G('pasos-del-robot','Pasos del robot',['4-5','5-6'],'funciones-ejecutivas','planificacion-secuencial','instrucciones-y-meta','multi-instruction','Planificar una secuencia corta de instrucciones para alcanzar una meta visible.','elegir y ejecutar pasos en orden antes de mover el robot','completar la ruta exacta sin pasos extra ni omisiones','aumentar de dos a cuatro instrucciones y añadir una decisión intermedia'),
G('que-flota-aqui','¿Qué flota aquí?',['3-4','4-5','5-6'],'ciencia','prediccion-cientifica','material-y-flotacion','experiment','Predecir el comportamiento de objetos cotidianos en agua y contrastar la hipótesis.','escoger flota o se hunde y después revelar el resultado del experimento','acertar la predicción a partir del material y la forma del objeto','introducir objetos huecos, macizos y materiales menos evidentes'),
G('palabras-que-terminan-igual','Palabras que terminan igual',['4-5','5-6'],'conciencia-fonologica','rima','terminacion-sonora','listen-choose','Reconocer palabras que comparten una terminación sonora sencilla.','escuchar o leer una palabra modelo y elegir la que rima entre distractores','seleccionar la palabra con terminación sonora equivalente','pasar de rimas muy contrastadas a terminaciones fonológicamente próximas'),
G('prepara-la-mochila','Prepara la mochila',['3-4','4-5','5-6'],'autonomia','planificacion-cotidiana','objeto-segun-actividad','context-choice','Seleccionar objetos adecuados para una actividad cotidiana anticipando necesidades.','observar el destino o actividad y escoger los objetos necesarios entre distractores','elegir solo los elementos funcionalmente necesarios para la situación','añadir dos condiciones simultáneas como clima y actividad'),
G('construye-la-mitad','Construye la mitad',['4-5','5-6'],'geometria','simetria-espacial','reflejo-de-formas','geometry-build','Completar una figura sencilla aplicando simetría respecto a un eje visible.','observar media figura y escoger la pieza que completa su reflejo','seleccionar la mitad que produce una figura simétrica completa','variar orientación del eje y usar formas compuestas')
]);
const merged=[...E.merged,...GAMES],errors=P.validateCatalog(GAMES),clones=P.cloneGroups(merged);
if(errors.length)console.error('Mundo Mimo V2 v360 catalog errors',errors);if(clones.length)console.error('Mundo Mimo V2 v360 clone groups',clones);
globalThis.MundoMimoV2ExpansionV360=Object.freeze({version:360,games:GAMES,errors,cloneGroups:clones,merged:Object.freeze(merged)});
})();