(()=>{'use strict';
const P=globalThis.MundoMimoV2,E=globalThis.MundoMimoV2ExpansionV410;if(!P||!E)throw new Error('Mundo Mimo V2 v420 catalog dependencies missing');
const G=(id,name,ages,area,skill,subskill,mechanic,objective,interaction,win,progression)=>Object.freeze({id,name,ages,area,skill,subskill,mechanic,objective,rules:Object.freeze({interaction,win,progression}),levels:12,feedback:Object.freeze({correct:'descriptivo-breve',incorrect:'pista-gradual'}),hints:Object.freeze(['modelado','reduccion-distractores','repeticion-posterior']),accessibility:Object.freeze(['visual','audio','touch','reduced-motion'])});
const GAMES=Object.freeze([
G('toca-y-aparece','Toca y aparece',['0-1','1-2'],'atencion','permanencia-del-objeto','anticipacion-visual','cause-effect','Reforzar atención conjunta y permanencia del objeto mediante aparición contingente.','tocar una zona grande para revelar un personaje oculto y anticipar dónde reaparecerá','activar correctamente las tres apariciones de la ronda','pasar de una única zona a dos posiciones visuales con mayor espera'),
G('accion-y-objeto','Acción y objeto',['1-2','2-3'],'lenguaje','vocabulario-funcional','verbo-y-objeto','semantic-association','Relacionar acciones cotidianas con el objeto que permite realizarlas.','elegir entre objetos familiares el que completa una acción verbal','seleccionar el objeto funcionalmente asociado a la acción','aumentar distractores y usar acciones menos frecuentes'),
G('cuenta-los-pasos','Cuenta los pasos',['2-3','3-4'],'matematicas','conteo-inicial','correspondencia-movimiento-numero','one-to-one-distribute','Vincular cada acción motora simulada con una unidad de conteo estable.','tocar exactamente tantas huellas como indica el número objetivo','alcanzar el objetivo sin quedarse corto ni excederse','progresar de 2-3 a 5 unidades y reducir apoyos visuales'),
G('familias-de-palabras','Familias de palabras',['3-4','4-5'],'lenguaje','categorias-semanticas','pertenencia-a-categoria','category-sort','Agrupar vocabulario por categorías semánticas comprensibles para la edad.','seleccionar los elementos que pertenecen a la categoría nombrada','identificar todos los miembros correctos sin incluir intrusos','pasar de categorías concretas a relaciones funcionales cercanas'),
G('antes-despues-y-a-la-vez','Antes, después y a la vez',['4-5','5-6'],'funciones-ejecutivas','razonamiento-temporal','relaciones-temporales','sequence-complete','Comprender relaciones temporales entre acciones y eventos cotidianos.','elegir la relación temporal que completa una escena de dos acciones','seleccionar antes, después o a la vez según la situación','introducir secuencias de tres eventos y dependencias implícitas'),
G('pistas-del-bosque','Pistas del bosque',['5-6'],'logica','inferencia-por-pistas','deduccion-multicriterio','logic-grid','Resolver una deducción sencilla combinando dos pistas independientes.','leer dos pistas breves y elegir el único animal que cumple ambas','seleccionar la opción compatible con todas las pistas','aumentar de dos a tres restricciones y añadir distractores parcialmente válidos')
]);
const merged=[...E.merged,...GAMES],errors=P.validateCatalog(GAMES),clones=P.cloneGroups(merged);
if(errors.length)console.error('Mundo Mimo V2 v420 catalog errors',errors);if(clones.length)console.error('Mundo Mimo V2 v420 clone groups',clones);
globalThis.MundoMimoV2ExpansionV420=Object.freeze({version:420,games:GAMES,errors,cloneGroups:clones,merged:Object.freeze(merged)});
})();