(()=>{'use strict';
const P=globalThis.MundoMimoV2,S=globalThis.MundoMimoV2Seed,E=globalThis.MundoMimoV2ExpansionV250;if(!P||!S||!E)throw new Error('Mundo Mimo V2 v260 catalog dependencies missing');
const G=(id,name,ages,area,skill,subskill,mechanic,objective,interaction,win,progression)=>Object.freeze({id,name,ages,area,skill,subskill,mechanic,objective,rules:Object.freeze({interaction,win,progression}),levels:12,feedback:Object.freeze({correct:'descriptivo-breve',incorrect:'pista-gradual'}),hints:Object.freeze(['modelado','reduccion-distractores','repeticion-posterior']),accessibility:Object.freeze(['visual','audio','touch','reduced-motion'])});
const GAMES=Object.freeze([
G('toca-lo-que-escuchas','Toca lo que escuchas',['1-2','2-3'],'lenguaje','comprension-receptiva','instruccion-objeto','tap-target','Comprender una instrucción oral simple y responder tocando el objeto indicado.','escuchar una consigna breve y tocar un objetivo grande entre distractores','tocar el único objeto nombrado','aumentar distractores y combinar atributo + objeto'),
G('memoria-de-cartas','Memoria de cartas',['2-3','3-4'],'memoria','memoria-visual','localizacion-parejas','memory-cards','Recordar posiciones y encontrar parejas visuales ocultas.','destapar dos cartas cada vez y recordar su ubicación','encontrar todas las parejas sin ayuda directa','aumentar pares y similitud visual'),
G('completa-la-secuencia','Completa la secuencia',['3-4','4-5'],'funciones-ejecutivas','secuenciacion','orden-logico','sequence-complete','Inferir el siguiente paso de una secuencia funcional o temporal.','observar tres pasos y seleccionar el cuarto entre alternativas','elegir el paso que completa coherentemente la secuencia','usar secuencias más largas y relaciones causales menos evidentes'),
G('detective-visual','Detective visual',['2-3','3-4'],'atencion','reconocimiento-visual','atributos','visual-recognition','Reconocer un objetivo por combinación de forma, color o rasgo visible.','observar un modelo y localizar el elemento que comparte sus atributos relevantes','seleccionar el único estímulo visual equivalente','combinar dos atributos y reducir diferencias entre distractores'),
G('parejas-con-sentido','Parejas con sentido',['3-4','4-5'],'lenguaje','relaciones-semanticas','categoria-funcion','semantic-association','Relacionar conceptos por función, categoría o contexto de uso.','seleccionar dos elementos cuya relación semántica responda a una consigna','formar la asociación conceptual correcta','pasar de relaciones concretas a categorías y usos menos evidentes'),
G('elige-todos','Elige todos',['4-5','5-6'],'funciones-ejecutivas','control-inhibitorio','seleccion-multiple','multi-select','Mantener una regla activa y seleccionar todos los elementos que la cumplen sin incluir distractores.','marcar varios estímulos según una regla verbal y confirmar la selección','seleccionar exactamente el conjunto válido','añadir distractores y reglas dobles con negación sencilla')
]);
const merged=[...E.merged,...GAMES];const errors=P.validateCatalog(GAMES),clones=P.cloneGroups(merged);
if(errors.length)console.error('Mundo Mimo V2 v260 catalog errors',errors);if(clones.length)console.error('Mundo Mimo V2 v260 clone groups',clones);
globalThis.MundoMimoV2ExpansionV260=Object.freeze({version:260,games:GAMES,errors,cloneGroups:clones,merged:Object.freeze(merged)});
})();
