(()=>{'use strict';
const P=globalThis.MundoMimoV2,E=globalThis.MundoMimoV2ExpansionV380;if(!P||!E)throw new Error('Mundo Mimo V2 v390 catalog dependencies missing');
const G=(id,name,ages,area,skill,subskill,mechanic,objective,interaction,win,progression)=>Object.freeze({id,name,ages,area,skill,subskill,mechanic,objective,rules:Object.freeze({interaction,win,progression}),levels:12,feedback:Object.freeze({correct:'descriptivo-breve',incorrect:'pista-gradual'}),hints:Object.freeze(['modelado','reduccion-distractores','repeticion-posterior']),accessibility:Object.freeze(['visual','audio','touch','reduced-motion'])});
const GAMES=Object.freeze([
G('que-usamos-para','¿Qué usamos para...?',['2-3','3-4'],'mundo-cotidiano','funcion-de-objetos','objeto-y-accion','semantic-association','Relacionar objetos cotidianos con su función práctica en situaciones familiares.','leer o escuchar una acción y tocar el objeto que permite realizarla','elegir el objeto funcionalmente adecuado','pasar de dos a cuatro opciones y acciones menos evidentes'),
G('eco-fuerte-suave','Eco fuerte o suave',['2-3','3-4'],'musica','intensidad-sonora','fuerte-y-suave','sound-recognition','Discriminar cualitativamente sonidos fuertes y suaves sin depender de lectura.','escuchar una consigna sonora representada y clasificarla como fuerte o suave','identificar correctamente la intensidad objetivo','alternar secuencias de dos y tres intensidades y reducir apoyos visuales'),
G('serie-de-numeros','Serie de números',['4-5','5-6'],'matematicas','secuencias-numericas','numero-que-falta','sequence-complete','Completar secuencias numéricas ascendentes sencillas comprendiendo la regularidad.','observar una serie con un hueco y elegir el número que la completa','seleccionar el valor que mantiene el patrón numérico','progresar de incrementos de uno a patrones de dos en dos'),
G('frase-en-orden','Frase en orden',['5-6'],'lectoescritura','sintaxis-inicial','orden-de-palabras','story-order','Construir frases breves con orden sintáctico comprensible a partir de palabras conocidas.','tocar palabras desordenadas para formar una frase y comprobarla','construir la secuencia sujeto-verbo-complemento esperada','pasar de tres a cuatro palabras e introducir modificadores sencillos'),
G('detective-de-causas','Detective de causas',['4-5','5-6'],'ciencia','causa-y-efecto','inferir-causa','context-choice','Inferir una causa probable a partir de un efecto cotidiano observable.','observar un resultado y elegir entre varias causas posibles','seleccionar la causa coherente con la evidencia mostrada','usar efectos con causas menos directas y distractores plausibles'),
G('copia-el-modelo','Copia el modelo',['4-5','5-6'],'geometria','composicion-espacial','posicion-relativa','geometry-build','Reproducir una disposición espacial sencilla atendiendo a posición y orden relativo.','seleccionar piezas en el orden espacial indicado por un modelo','reconstruir la disposición objetivo completa','aumentar de tres a cuatro piezas y usar relaciones izquierda-centro-derecha')
]);
const merged=[...E.merged,...GAMES],errors=P.validateCatalog(GAMES),clones=P.cloneGroups(merged);
if(errors.length)console.error('Mundo Mimo V2 v390 catalog errors',errors);if(clones.length)console.error('Mundo Mimo V2 v390 clone groups',clones);
globalThis.MundoMimoV2ExpansionV390=Object.freeze({version:390,games:GAMES,errors,cloneGroups:clones,merged:Object.freeze(merged)});
})();