(()=>{'use strict';
const P=globalThis.MundoMimoV2,E=globalThis.MundoMimoV2ExpansionV310;if(!P||!E)throw new Error('Mundo Mimo V2 v320 catalog dependencies missing');
const G=(id,name,ages,area,skill,subskill,mechanic,objective,interaction,win,progression)=>Object.freeze({id,name,ages,area,skill,subskill,mechanic,objective,rules:Object.freeze({interaction,win,progression}),levels:12,feedback:Object.freeze({correct:'descriptivo-breve',incorrect:'pista-gradual'}),hints:Object.freeze(['modelado','reduccion-distractores','repeticion-posterior']),accessibility:Object.freeze(['visual','audio','touch','reduced-motion'])});
const GAMES=Object.freeze([
G('respira-con-mimo','Respira con Mimo',['2-3','3-4','4-5'],'emociones','autorregulacion','respiracion-guiada','hold-release','Practicar una pausa respiratoria breve como estrategia de calma, sin convertirla en ejercicio clínico.','mantener pulsado mientras el personaje inspira y soltar cuando aparece la señal de exhalar','completar el ciclo respetando la señal visual','pasar de un ciclo a pequeñas secuencias con ritmos lentos y predecibles'),
G('patrulla-del-reciclaje','Patrulla del reciclaje',['3-4','4-5','5-6'],'ciencia','clasificacion-ambiental','material-y-contenedor','category-sort','Relacionar residuos cotidianos sencillos con categorías de material de forma educativa.','clasificar objetos visuales en papel, envases u orgánico','ubicar todo el conjunto en su categoría objetivo','añadir distractores y objetos compuestos con apoyo contextual'),
G('siluetas-del-taller','Siluetas del taller',['2-3','3-4'],'geometria','percepcion-de-forma','contorno-y-objeto','fit-shape','Reconocer objetos por su contorno global y encajarlos en una silueta correspondiente.','elegir y encajar el objeto cuya forma coincide con la silueta mostrada','completar el encaje correcto','reducir pistas internas y usar contornos más parecidos'),
G('jardin-de-sumas','Jardín de sumas',['4-5','5-6'],'matematicas','composicion-de-cantidades','suma-visual','problem-solve','Componer una cantidad objetivo reuniendo dos grupos visibles de flores.','seleccionar dos macetas cuyas cantidades juntas alcanzan el objetivo','formar exactamente la suma solicitada','aumentar objetivos y ofrecer combinaciones alternativas equivalentes'),
G('eco-de-sonidos','Eco de sonidos',['3-4','4-5','5-6'],'memoria','memoria-auditiva-secuencial','orden-de-sonidos','auditory-memory','Retener y reproducir el orden de una secuencia corta de sonidos claramente diferenciados.','escuchar una secuencia de iconos sonoros y repetirla tocando los mismos elementos en orden','reproducir toda la secuencia sin alterar el orden','aumentar longitud de dos a cuatro sonidos y reducir repetición automática'),
G('quien-nos-ayuda','¿Quién nos ayuda?',['3-4','4-5','5-6'],'mundo-cotidiano','profesiones-y-funciones','persona-y-tarea','semantic-association','Relacionar profesiones cotidianas con la ayuda o tarea principal que realizan, evitando estereotipos de género.','leer o escuchar una necesidad cotidiana y elegir la profesión relacionada','asociar necesidad y función de forma coherente','incorporar profesiones menos familiares y varias pistas funcionales')
]);
const merged=[...E.merged,...GAMES],errors=P.validateCatalog(GAMES),clones=P.cloneGroups(merged);
if(errors.length)console.error('Mundo Mimo V2 v320 catalog errors',errors);if(clones.length)console.error('Mundo Mimo V2 v320 clone groups',clones);
globalThis.MundoMimoV2ExpansionV320=Object.freeze({version:320,games:GAMES,errors,cloneGroups:clones,merged:Object.freeze(merged)});
})();