(()=>{'use strict';
const P=globalThis.MundoMimoV2,E=globalThis.MundoMimoV2ExpansionV260;if(!P||!E)throw new Error('Mundo Mimo V2 v270 catalog dependencies missing');
const G=(id,name,ages,area,skill,subskill,mechanic,objective,interaction,win,progression)=>Object.freeze({id,name,ages,area,skill,subskill,mechanic,objective,rules:Object.freeze({interaction,win,progression}),levels:12,feedback:Object.freeze({correct:'descriptivo-breve',incorrect:'pista-gradual'}),hints:Object.freeze(['modelado','reduccion-distractores','repeticion-posterior']),accessibility:Object.freeze(['visual','audio','touch','reduced-motion'])});
const GAMES=Object.freeze([
G('de-menor-a-mayor','De menor a mayor',['3-4','4-5'],'matematicas','seriacion','magnitudes','sort-order','Ordenar varios elementos según una magnitud observable.','reordenar tres o cuatro objetos por tamaño de menor a mayor','todas las posiciones siguen la relación de tamaño','aumentar elementos y reducir diferencias perceptivas'),
G('familias-de-animales','Familias de animales',['2-3','3-4'],'ciencia','relaciones-biologicas','adulto-cria','connect-pairs','Relacionar animales adultos con sus crías.','conectar cada adulto con la cría correspondiente','completar todas las parejas biológicas','más parejas y especies visualmente próximas'),
G('dibuja-como-te-sientes','Dibuja cómo te sientes',['3-4','4-5','5-6'],'emociones','expresion-emocional','representacion-grafica','free-draw','Representar libremente una emoción mediante trazos y elementos visuales.','elegir una emoción y crear un dibujo libre asociado','realizar una creación con interacción gráfica suficiente','añadir colores, símbolos y una breve elección sobre el significado'),
G('que-instrumento-suena','¿Qué instrumento suena?',['2-3','3-4','4-5'],'musica','discriminacion-auditiva','timbre-instrumental','sound-recognition','Distinguir timbres de instrumentos cotidianos.','escuchar un patrón sonoro representado y seleccionar su instrumento','identificar el instrumento correspondiente al timbre objetivo','ampliar familias instrumentales y similitud tímbrica'),
G('casitas-logicas','Casitas lógicas',['4-5','5-6'],'logica','deduccion','restricciones-espaciales','logic-grid','Resolver una colocación sencilla a partir de pistas excluyentes.','leer o escuchar dos pistas y ubicar personajes en casas posibles','asignar cada personaje a una posición compatible con todas las pistas','añadir posiciones y combinar restricciones positivas y negativas'),
G('que-necesitas-ahora','¿Qué necesitas ahora?',['2-3','3-4','4-5'],'autonomia','decision-cotidiana','necesidad-accion','context-choice','Elegir una acción u objeto apropiado para una necesidad cotidiana.','observar una situación cotidiana y elegir la respuesta funcional adecuada','seleccionar la opción que resuelve la necesidad sin riesgo','introducir contextos menos explícitos y alternativas plausibles')
]);
const merged=[...E.merged,...GAMES],errors=P.validateCatalog(GAMES),clones=P.cloneGroups(merged);
if(errors.length)console.error('Mundo Mimo V2 v270 catalog errors',errors);if(clones.length)console.error('Mundo Mimo V2 v270 clone groups',clones);
globalThis.MundoMimoV2ExpansionV270=Object.freeze({version:270,games:GAMES,errors,cloneGroups:clones,merged:Object.freeze(merged)});
})();
