(()=>{'use strict';
const P=globalThis.MundoMimoV2,E=globalThis.MundoMimoV2ExpansionV280;if(!P||!E)throw new Error('Mundo Mimo V2 v290 catalog dependencies missing');
const G=(id,name,ages,area,skill,subskill,mechanic,objective,interaction,win,progression)=>Object.freeze({id,name,ages,area,skill,subskill,mechanic,objective,rules:Object.freeze({interaction,win,progression}),levels:12,feedback:Object.freeze({correct:'descriptivo-breve',incorrect:'pista-gradual'}),hints:Object.freeze(['modelado','reduccion-distractores','repeticion-posterior']),accessibility:Object.freeze(['visual','audio','touch','reduced-motion'])});
const GAMES=Object.freeze([
G('espera-y-descubre','Espera y descubre',['0-1','1-2'],'funciones-ejecutivas','control-inhibitorio','espera-breve','hold-release','Practicar una espera breve antes de actuar y observar un cambio predecible.','mantener pulsado un objeto hasta que la señal visual indique que puede soltarse','soltar después de la señal y no antes','aumentar gradualmente la espera sin superar intervalos apropiados para la edad'),
G('escalera-de-tamanos','Escalera de tamaños',['2-3','3-4'],'matematicas','seriacion','orden-de-magnitud','sort-order','Ordenar tres objetos por tamaño de menor a mayor usando comparación perceptiva.','tocar objetos en el orden de tamaño solicitado','seleccionar la secuencia completa de menor a mayor','pasar de diferencias muy evidentes a tamaños más próximos y cuatro elementos'),
G('une-emocion-y-motivo','Une emoción y motivo',['3-4','4-5'],'emociones','comprension-emocional','causa-emocion','connect-pairs','Relacionar situaciones cotidianas sencillas con la emoción que probablemente provocan.','seleccionar una situación y conectarla con la emoción coherente','completar todas las conexiones situación-emoción','incorporar emociones próximas y situaciones con más de una pista contextual'),
G('completa-la-frase','Completa la frase',['4-5','5-6'],'lenguaje','comprension-gramatical','estructura-de-frase','fill-missing','Elegir la palabra que completa con sentido una frase oral o escrita sencilla.','leer o escuchar una frase incompleta y elegir la palabra que encaja semántica y gramaticalmente','completar la frase con la opción coherente','añadir concordancia, verbos y distractores semánticamente próximos'),
G('balanza-de-cantidades','Balanza de cantidades',['4-5','5-6'],'matematicas','equivalencia','composicion-y-equilibrio','problem-solve','Construir una cantidad equivalente a otra combinando grupos visuales.','seleccionar una combinación de cantidades para igualar el objetivo de la balanza','alcanzar exactamente la cantidad objetivo','usar más sumandos, cantidades mayores y una pieza sobrante distractora'),
G('codigo-de-flechas','Código de flechas',['5-6'],'funciones-ejecutivas','planificacion','instrucciones-espaciales','multi-instruction','Retener y ejecutar una secuencia de instrucciones espaciales representadas por flechas.','observar un código breve y reproducirlo en el mismo orden','repetir la secuencia completa sin alterar el orden','aumentar longitud, introducir giros y retirar progresivamente el modelo')
]);
const merged=[...E.merged,...GAMES],errors=P.validateCatalog(GAMES),clones=P.cloneGroups(merged);
if(errors.length)console.error('Mundo Mimo V2 v290 catalog errors',errors);if(clones.length)console.error('Mundo Mimo V2 v290 clone groups',clones);
globalThis.MundoMimoV2ExpansionV290=Object.freeze({version:290,games:GAMES,errors,cloneGroups:clones,merged:Object.freeze(merged)});
})();