(()=>{'use strict';
const P=globalThis.MundoMimoV2,E=globalThis.MundoMimoV2ExpansionV330;if(!P||!E)throw new Error('Mundo Mimo V2 v340 catalog dependencies missing');
const G=(id,name,ages,area,skill,subskill,mechanic,objective,interaction,win,progression)=>Object.freeze({id,name,ages,area,skill,subskill,mechanic,objective,rules:Object.freeze({interaction,win,progression}),levels:12,feedback:Object.freeze({correct:'descriptivo-breve',incorrect:'pista-gradual'}),hints:Object.freeze(['modelado','reduccion-distractores','repeticion-posterior']),accessibility:Object.freeze(['visual','audio','touch','reduced-motion'])});
const GAMES=Object.freeze([
G('semillas-que-crecen','Semillas que crecen',['2-3','3-4'],'ciencia','secuenciacion-natural','ciclo-de-planta','step-order','Comprender una secuencia natural sencilla desde semilla hasta planta.','ordenar tres escenas de crecimiento en una línea temporal','colocar semilla, brote y planta en orden causal','introducir cuatro etapas y cambios estacionales'),
G('reloj-de-rutinas','El reloj de las rutinas',['2-3','3-4','4-5'],'autonomia','organizacion-cotidiana','momento-y-accion','context-choice','Relacionar momentos del día con rutinas apropiadas y fomentar autonomía cotidiana.','observar un momento del día y elegir la acción que corresponde','seleccionar una rutina coherente con mañana, tarde o noche','incorporar secuencias de dos acciones y contextos menos explícitos'),
G('palabras-en-trozos','Palabras en trozos',['4-5','5-6'],'conciencia-fonologica','segmentacion-silabica','silabas-en-orden','sort-order','Segmentar y recomponer palabras familiares a partir de sus sílabas.','ordenar tarjetas silábicas para reconstruir una palabra apoyada por imagen','formar la palabra objetivo con todas sus sílabas en el orden correcto','pasar de dos a tres sílabas y retirar apoyo visual'),
G('figuras-que-giran','Figuras que giran',['4-5','5-6'],'geometria','rotacion-mental','orientacion-de-formas','visual-recognition','Reconocer una misma figura aunque cambie su orientación espacial.','comparar un modelo con varias figuras rotadas y elegir la equivalente','identificar la misma forma sin dejarse llevar por su giro','aumentar similitud entre distractores y usar composiciones de varias piezas'),
G('el-turno-es-de','El turno es de…',['3-4','4-5','5-6'],'habilidades-sociales','turnos-y-espera','reglas-compartidas','consequence-choice','Practicar la elección de conductas respetuosas cuando varias personas quieren participar.','observar una escena social y elegir qué acción respeta el turno','seleccionar la conducta que permite continuar el juego compartido','introducir acuerdos, negociación y más de una estrategia prosocial aceptable'),
G('escucha-y-encuentra','Escucha y encuentra',['1-2','2-3','3-4'],'lenguaje','comprension-receptiva','instruccion-de-dos-rasgos','listen-choose','Comprender instrucciones orales o visuales breves que combinan objeto y atributo.','atender a una consigna de dos rasgos y tocar el elemento que cumple ambos','elegir exactamente el objeto descrito por categoría y atributo','pasar de un rasgo a dos y luego incorporar posición espacial')
]);
const merged=[...E.merged,...GAMES],errors=P.validateCatalog(GAMES),clones=P.cloneGroups(merged);
if(errors.length)console.error('Mundo Mimo V2 v340 catalog errors',errors);if(clones.length)console.error('Mundo Mimo V2 v340 clone groups',clones);
globalThis.MundoMimoV2ExpansionV340=Object.freeze({version:340,games:GAMES,errors,cloneGroups:clones,merged:Object.freeze(merged)});
})();