(()=>{'use strict';
const P=globalThis.MundoMimoV2,E=globalThis.MundoMimoV2ExpansionV360;if(!P||!E)throw new Error('Mundo Mimo V2 v370 catalog dependencies missing');
const G=(id,name,ages,area,skill,subskill,mechanic,objective,interaction,win,progression)=>Object.freeze({id,name,ages,area,skill,subskill,mechanic,objective,rules:Object.freeze({interaction,win,progression}),levels:12,feedback:Object.freeze({correct:'descriptivo-breve',incorrect:'pista-gradual'}),hints:Object.freeze(['modelado','reduccion-distractores','repeticion-posterior']),accessibility:Object.freeze(['visual','audio','touch','reduced-motion'])});
const GAMES=Object.freeze([
G('sigue-el-destello','Sigue el destello',['1-2','2-3'],'atencion','seguimiento-visual','objetivo-en-movimiento','tap-target','Mantener la atención visual sobre un objetivo que cambia de posición y responder cuando se detiene.','observar una luz que recorre tres posiciones y tocarla solo cuando queda estable','tocar la posición final correcta después del recorrido','aumentar longitud del recorrido y añadir distractores estáticos'),
G('ordena-el-desayuno','Ordena el desayuno',['3-4','4-5'],'autonomia','secuenciacion-cotidiana','preparacion-de-comida','step-order','Ordenar una rutina cotidiana sencilla respetando una secuencia funcional.','colocar tres acciones del desayuno en el orden necesario antes de comprobar','reconstruir la secuencia completa sin saltos','pasar de tres a cinco pasos y añadir acciones irrelevantes'),
G('eco-de-palmas-largas','Eco de palmas largas',['3-4','4-5','5-6'],'musica','memoria-auditiva-secuencial','patron-de-pulsos','auditory-memory','Retener y reproducir una secuencia breve de pulsos con distinta longitud.','escuchar un patrón de palmas y repetirlo pulsando los pads en el mismo orden','reproducir la secuencia exacta','aumentar de dos a cinco pulsos y mezclar pausas'),
G('que-cambia-si','¿Qué cambia si...?',['4-5','5-6'],'ciencia','causalidad-cientifica','variable-y-resultado','simple-simulation','Anticipar cómo cambia un resultado cuando se modifica una variable observable.','elegir entre dos cambios de una situación y predecir su consecuencia antes de revelar el resultado','seleccionar la consecuencia coherente con la variable modificada','introducir dos variables y resultados menos evidentes'),
G('vecinos-del-numero','Vecinos del número',['4-5','5-6'],'matematicas','orden-numerico','anterior-y-siguiente','fill-missing','Identificar el número anterior y posterior dentro de una secuencia numérica corta.','observar una secuencia con un hueco y escoger el valor que la completa','completar correctamente el hueco numérico','ampliar rango y usar saltos regulares de dos en dos'),
G('construye-la-historia','Construye la historia',['5-6'],'lenguaje','planificacion-narrativa','inicio-nudo-desenlace','narrative-puzzle','Construir una historia breve con inicio, problema y desenlace coherentes.','elegir una tarjeta para cada fase narrativa y comprobar coherencia entre las tres','formar una secuencia narrativa causal completa','añadir alternativas plausibles y relaciones causa-consecuencia más sutiles')
]);
const merged=[...E.merged,...GAMES],errors=P.validateCatalog(GAMES),clones=P.cloneGroups(merged);
if(errors.length)console.error('Mundo Mimo V2 v370 catalog errors',errors);if(clones.length)console.error('Mundo Mimo V2 v370 clone groups',clones);
globalThis.MundoMimoV2ExpansionV370=Object.freeze({version:370,games:GAMES,errors,cloneGroups:clones,merged:Object.freeze(merged)});
})();