(()=>{'use strict';
const P=globalThis.MundoMimoV2,E=globalThis.MundoMimoV2ExpansionV370;if(!P||!E)throw new Error('Mundo Mimo V2 v380 catalog dependencies missing');
const G=(id,name,ages,area,skill,subskill,mechanic,objective,interaction,win,progression)=>Object.freeze({id,name,ages,area,skill,subskill,mechanic,objective,rules:Object.freeze({interaction,win,progression}),levels:12,feedback:Object.freeze({correct:'descriptivo-breve',incorrect:'pista-gradual'}),hints:Object.freeze(['modelado','reduccion-distractores','repeticion-posterior']),accessibility:Object.freeze(['visual','audio','touch','reduced-motion'])});
const GAMES=Object.freeze([
G('gestos-de-mimo','Gestos de Mimo',['1-2','2-3'],'emociones','imitacion-emocional','gesto-y-expresion','gesture-match','Relacionar un gesto facial sencillo con una emoción cotidiana reconocible.','observar una cara de Mimo y tocar la emoción que corresponde a su gesto','elegir la emoción coherente con ojos y boca','pasar de dos a cuatro emociones y reducir pistas visuales'),
G('pasos-hasta-casa','Pasos hasta casa',['2-3','3-4'],'matematicas','conteo-con-movimiento','correspondencia-paso-numero','one-to-one-distribute','Coordinar conteo inicial y desplazamiento haciendo corresponder un toque con cada paso.','tocar avanzar exactamente tantas veces como indica el número objetivo antes de comprobar','llegar al número de pasos pedido sin pasarse','aumentar de dos a seis pasos e introducir objetivos consecutivos'),
G('balanza-de-objetos','Balanza de objetos',['4-5','5-6'],'matematicas','seriacion-por-peso','comparacion-ligero-pesado','sort-order','Ordenar objetos cotidianos por peso relativo usando conocimiento y comparación cualitativa.','seleccionar tres objetos desde el más ligero hasta el más pesado y comprobar el orden','construir la serie completa de menor a mayor peso','pasar a cuatro objetos y diferencias de peso menos evidentes'),
G('palabra-intrusa','La palabra intrusa',['4-5','5-6'],'lenguaje','categorias-semanticas','pertenencia-a-categoria','odd-one-out','Detectar qué palabra no pertenece a una categoría semántica compartida.','escuchar o leer tres palabras y tocar la que no pertenece al mismo grupo','identificar la palabra semánticamente ajena','usar categorías más próximas y cuatro opciones'),
G('sombras-al-sol','Sombras al sol',['4-5','5-6'],'ciencia','luz-y-sombras','posicion-de-la-luz','simple-simulation','Predecir cómo cambia una sombra cuando cambia la posición de una fuente de luz.','observar la posición del sol y elegir hacia qué lado se proyectará la sombra','seleccionar la dirección opuesta a la fuente de luz','variar altura y posición de la luz con tres alternativas'),
G('plan-de-dos-misiones','Plan de dos misiones',['5-6'],'funciones-ejecutivas','planificacion-de-tareas','prioridad-y-dependencia','multi-instruction','Planificar dos tareas sencillas respetando una dependencia explícita antes de actuar.','leer dos misiones y seleccionar primero la acción necesaria para desbloquear la segunda','ejecutar ambas tareas en el orden que respeta la dependencia','añadir una tercera acción distractora y dependencias menos directas')
]);
const merged=[...E.merged,...GAMES],errors=P.validateCatalog(GAMES),clones=P.cloneGroups(merged);
if(errors.length)console.error('Mundo Mimo V2 v380 catalog errors',errors);if(clones.length)console.error('Mundo Mimo V2 v380 clone groups',clones);
globalThis.MundoMimoV2ExpansionV380=Object.freeze({version:380,games:GAMES,errors,cloneGroups:clones,merged:Object.freeze(merged)});
})();