(()=>{'use strict';
const P=globalThis.MundoMimoV2,E=globalThis.MundoMimoV2ExpansionV340;if(!P||!E)throw new Error('Mundo Mimo V2 v350 catalog dependencies missing');
const G=(id,name,ages,area,skill,subskill,mechanic,objective,interaction,win,progression)=>Object.freeze({id,name,ages,area,skill,subskill,mechanic,objective,rules:Object.freeze({interaction,win,progression}),levels:12,feedback:Object.freeze({correct:'descriptivo-breve',incorrect:'pista-gradual'}),hints:Object.freeze(['modelado','reduccion-distractores','repeticion-posterior']),accessibility:Object.freeze(['visual','audio','touch','reduced-motion'])});
const GAMES=Object.freeze([
G('quien-hace-ese-sonido','¿Quién hace ese sonido?',['1-2','2-3','3-4'],'lenguaje','asociacion-auditiva','fuente-y-sonido','sound-recognition','Relacionar sonidos cotidianos con la fuente que los produce.','escuchar o leer una onomatopeya y escoger su fuente entre categorías distintas','elegir el objeto o ser que produce el sonido objetivo','pasar de sonidos muy contrastados a fuentes de la misma categoría'),
G('carrera-de-longitudes','Carrera de longitudes',['3-4','4-5','5-6'],'matematicas','seriacion-de-medidas','comparacion-de-longitud','sort-order','Ordenar objetos por longitud usando comparación visual relativa.','seleccionar objetos desde el más corto hasta el más largo','construir una serie estrictamente creciente sin repetir objetos','aumentar a cuatro elementos y reducir diferencias perceptivas'),
G('huellas-y-animales','Huellas y animales',['2-3','3-4','4-5'],'ciencia','observacion-de-indicios','animal-por-huella','visual-recognition','Inferir qué animal corresponde a una huella visual sencilla.','comparar una huella modelo con varias posibles fuentes animales','elegir el animal cuya anatomía es coherente con la huella','introducir huellas parecidas y pistas de hábitat'),
G('mi-cuerpo-me-avisa','Mi cuerpo me avisa',['3-4','4-5','5-6'],'emociones','conciencia-corporal','sensacion-y-emocion','context-choice','Reconocer señales corporales sencillas asociadas a estados emocionales cotidianos.','observar una situación y una señal corporal y escoger la emoción más coherente','relacionar contexto, sensación corporal y emoción sin etiquetar como diagnóstico','incorporar emociones próximas y estrategias de autorregulación no clínicas'),
G('reparte-el-camino','Reparte el camino',['3-4','4-5','5-6'],'matematicas','correspondencia-y-reparto','distribucion-equitativa','one-to-one-distribute','Comprender el reparto uno-a-uno y la igualdad de pequeñas colecciones.','repartir fichas alternando destinos hasta agotar la colección','dejar la misma cantidad en cada destino cuando el total lo permite','aumentar destinos, totales y detectar cuándo sobra una unidad'),
G('antes-o-despues','¿Antes o después?',['3-4','4-5','5-6'],'lenguaje','comprension-narrativa','relacion-temporal','step-order','Comprender relaciones temporales sencillas entre acciones de una historia.','leer o escuchar tres acciones y reconstruir el orden temporal por causalidad','colocar inicio, acción intermedia y resultado en secuencia coherente','retirar marcadores temporales e introducir cuatro escenas')
]);
const merged=[...E.merged,...GAMES],errors=P.validateCatalog(GAMES),clones=P.cloneGroups(merged);
if(errors.length)console.error('Mundo Mimo V2 v350 catalog errors',errors);if(clones.length)console.error('Mundo Mimo V2 v350 clone groups',clones);
globalThis.MundoMimoV2ExpansionV350=Object.freeze({version:350,games:GAMES,errors,cloneGroups:clones,merged:Object.freeze(merged)});
})();