(()=>{'use strict';
const P=globalThis.MundoMimoV2,E=globalThis.MundoMimoV2ExpansionV400;if(!P||!E)throw new Error('Mundo Mimo V2 v410 catalog dependencies missing');
const G=(id,name,ages,area,skill,subskill,mechanic,objective,interaction,win,progression)=>Object.freeze({id,name,ages,area,skill,subskill,mechanic,objective,rules:Object.freeze({interaction,win,progression}),levels:12,feedback:Object.freeze({correct:'descriptivo-breve',incorrect:'pista-gradual'}),hints:Object.freeze(['modelado','reduccion-distractores','repeticion-posterior']),accessibility:Object.freeze(['visual','audio','touch','reduced-motion'])});
const GAMES=Object.freeze([
G('sonido-y-objeto','Sonido y objeto',['1-2','2-3'],'lenguaje','comprension-auditiva','sonido-y-referente','listen-choose','Relacionar un sonido cotidiano descrito o reproducido con el objeto que lo produce.','escuchar una pista sonora y elegir entre objetos familiares','seleccionar el objeto que corresponde al sonido objetivo','pasar de dos a cuatro opciones y de sonidos muy distintos a sonidos cercanos'),
G('ordena-por-uso','Ordena por uso',['2-3','3-4'],'mundo-cotidiano','funcion-de-objetos','clasificacion-funcional','category-sort','Clasificar objetos cotidianos según la acción o situación en la que se utilizan.','colocar cada objeto en la categoría de uso correcta','clasificar todos los objetos sin mezclar funciones','aumentar categorías y añadir objetos que admiten asociaciones próximas'),
G('camino-incompleto','Camino incompleto',['3-4','4-5'],'logica','secuencias-visuales','continuidad-de-ruta','sequence-complete','Completar una secuencia de señales para mantener la continuidad de un recorrido.','observar una ruta con un paso ausente y elegir la señal que completa el patrón','seleccionar la pieza que hace coherente toda la secuencia','progresar de alternancias simples a reglas de dos atributos'),
G('tren-de-silabas','Tren de sílabas',['4-5','5-6'],'conciencia-fonologica','segmentacion-silabica','orden-de-silabas','sort-order','Reconstruir palabras conocidas ordenando sus sílabas en la secuencia oral correcta.','tocar sílabas desordenadas para formar la palabra indicada','reproducir el orden silábico completo de la palabra','pasar de palabras bisílabas a trisílabas con sílabas distractoras'),
G('plan-de-manana','Plan de mañana',['4-5','5-6'],'funciones-ejecutivas','planificacion-cotidiana','dependencias-de-tareas','step-order','Planificar una rutina breve respetando dependencias entre acciones cotidianas.','ordenar acciones de una rutina usando relaciones de antes y después','crear una secuencia funcional en la que todas las dependencias se respetan','aumentar de tres a cinco pasos e introducir alternativas irrelevantes'),
G('balanza-de-puntos','Balanza de puntos',['5-6'],'matematicas','equivalencia-de-cantidades','composicion-aditiva','problem-solve','Construir una cantidad equivalente combinando dos grupos numéricos sencillos.','elegir dos cantidades cuya suma iguale el objetivo mostrado en la balanza','componer exactamente la cantidad objetivo sin excederla','ampliar objetivos de cinco a diez y ofrecer combinaciones con distractores próximos')
]);
const merged=[...E.merged,...GAMES],errors=P.validateCatalog(GAMES),clones=P.cloneGroups(merged);
if(errors.length)console.error('Mundo Mimo V2 v410 catalog errors',errors);if(clones.length)console.error('Mundo Mimo V2 v410 clone groups',clones);
globalThis.MundoMimoV2ExpansionV410=Object.freeze({version:410,games:GAMES,errors,cloneGroups:clones,merged:Object.freeze(merged)});
})();