(()=>{'use strict';
const P=globalThis.MundoMimoV2,S=globalThis.MundoMimoV2Seed;if(!P||!S)throw new Error('Mundo Mimo V2 platform/catalog missing');
const $=id=>document.getElementById(id),ageBar=$('ageBar'),gameGrid=$('gameGrid'),stage=$('stage'),play=$('play'),feedback=$('feedback'),title=$('gameTitle'),meta=$('gameMeta'),bar=$('progressBar');
const IMPLEMENTED=['luces-y-sonidos','encaja-grande','torre-de-mimo','parejas-sonoras','busca-en-la-casa','ritmo-de-pipa','camino-del-conejo','cajas-de-colores','puzzle-del-bosque','laberinto-de-lio','ordenamos-el-dia','detectives-de-diferencias'];
let age='2-3',current=null,round=0,score=0,locked=false,cleanup=[];
const stateKey='mimo-v2-runtime-200';
const read=()=>{try{return JSON.parse(localStorage.getItem(stateKey)||'{}')}catch{return {}}};
const write=v=>{try{localStorage.setItem(stateKey,JSON.stringify(v))}catch{}};
function persist(ok){const s=read();s.games??={};const g=s.games[current.id]??={plays:0,success:0};g.plays++;if(ok)g.success++;g.last=Date.now();s.games[current.id]=g;s.age=age;write(s)}
function clear(){cleanup.splice(0).forEach(fn=>{try{fn()}catch{}});play.innerHTML='';feedback.textContent='';locked=false}
function finish(ok,msg){if(locked)return;locked=true;persist(ok);feedback.textContent=msg;score+=ok?1:0;bar.style.width=Math.min(100,((round+1)/3)*100)+'%';setTimeout(()=>{round++;if(round>=3){feedback.textContent=`¡Sesión completada! ${score}/3`;play.innerHTML='<button class="action" data-again>Jugar otra vez</button>';play.querySelector('[data-again]').onclick=()=>start(current.id);return}renderRound()},500)}
function eligible(g){return g.ages.includes(age)}
function renderAges(){ageBar.innerHTML=P.ageBands.map(b=>`<button type="button" data-age="${b.id}" aria-pressed="${b.id===age}">${b.label}</button>`).join('');ageBar.querySelectorAll('button').forEach(b=>b.onclick=()=>{age=b.dataset.age;renderAges();renderGames()})}
function renderGames(){const games=S.games.filter(g=>IMPLEMENTED.includes(g.id)&&eligible(g));gameGrid.innerHTML=games.map(g=>`<button class="gameCard" type="button" data-game="${g.id}"><b>${g.name}</b><small>${g.skill} · ${g.mechanic}</small></button>`).join('')||'<p>No hay todavía juegos jugables para esta franja en este núcleo.</p>';gameGrid.querySelectorAll('[data-game]').forEach(b=>b.onclick=()=>start(b.dataset.game))}
function start(id){current=S.games.find(g=>g.id===id);if(!current)return;round=0;score=0;stage.hidden=false;title.textContent=current.name;meta.textContent=`${current.area} · ${current.skill}`;bar.style.width='0';renderRound();stage.scrollIntoView({block:'start'})}
function renderRound(){clear();if(!current)return;const fn=handlers[current.id];if(!fn){play.textContent='Juego aún no implementado';return}fn()}
function tapCause(){play.innerHTML='<div><p>Toca el sol para despertar el cielo.</p><button class="bigTarget" type="button" aria-label="Sol">☀️</button></div>';const b=play.querySelector('button');let taps=0;b.onclick=()=>{taps++;b.textContent=['🌞','🌈','✨'][Math.min(taps-1,2)];if(taps>=2)finish(true,'¡Tu acción cambió la escena!')}}
function fitShape(){play.innerHTML='<div><p>Arrastra la estrella hasta su hueco.</p><div class="dropzone" data-drop tabindex="0">☆</div><div class="draggable" draggable="true" tabindex="0" role="button" aria-label="Estrella para encajar">⭐</div></div>';const d=play.querySelector('.draggable'),z=play.querySelector('[data-drop]');const ok=()=>finish(true,'¡Encajó!');d.addEventListener('dragstart',e=>e.dataTransfer?.setData('text/plain','star'));z.addEventListener('dragover',e=>e.preventDefault());z.addEventListener('drop',e=>{e.preventDefault();ok()});d.addEventListener('click',ok)}
function tower(){const heights=[58,78,98];play.innerHTML=`<div><p>Construye una torre de 3 bloques, de mayor a menor.</p><div class="blocks" data-tower></div><div class="choices">${heights.sort(()=>Math.random()-.5).map(h=>`<button class="block" style="height:${h}px" data-h="${h}" aria-label="Bloque ${h}"></button>`).join('')}</div></div>`;const tower=play.querySelector('[data-tower]');let last=Infinity,count=0;play.querySelectorAll('[data-h]').forEach(b=>b.onclick=()=>{const h=Number(b.dataset.h);if(h>=last){feedback.textContent='Prueba con un bloque más pequeño.';return}last=h;count++;tower.appendChild(b);if(count===3)finish(true,'¡Torre estable!')})}
function soundPairs(){const symbols=['🐶','🔔','🚗'],cards=[...symbols,...symbols].sort(()=>Math.random()-.5);let open=[],done=0;play.innerHTML=`<div><p>Encuentra las parejas de sonidos.</p><div class="memoryGrid">${cards.map((s,i)=>`<button type="button" data-card="${i}" data-s="${s}" aria-label="Tarjeta sonora ${i+1}">🔊</button>`).join('')}</div></div>`;play.querySelectorAll('[data-card]').forEach(b=>b.onclick=()=>{if(b.dataset.open)return;b.dataset.open='1';b.textContent=b.dataset.s;open.push(b);if(open.length===2){const[a,c]=open;if(a.dataset.s===c.dataset.s){a.disabled=c.disabled=true;done+=2;open=[];if(done===cards.length)finish(true,'¡Recordaste todos los sonidos!')}else setTimeout(()=>{a.textContent=c.textContent='🔊';delete a.dataset.open;delete c.dataset.open;open=[]},450)}})}
function hiddenObject(){const positions=[[10,18],[68,20],[35,62],[76,68],[8,70]],target=Math.floor(Math.random()*positions.length);play.innerHTML='<div><p>Encuentra la mariposa escondida.</p><div class="scene"></div></div>';const scene=play.querySelector('.scene');positions.forEach((p,i)=>{const b=document.createElement('button');b.type='button';b.className='hiddenObj';b.style.left=p[0]+'%';b.style.top=p[1]+'%';b.textContent=i===target?'🦋':['🌼','🌳','☁️','🐞','🍄'][i];b.setAttribute('aria-label',i===target?'Mariposa':'Elemento del paisaje');b.onclick=()=>i===target?finish(true,'¡La encontraste!'):(feedback.textContent='Sigue buscando…');scene.appendChild(b)})}
function rhythm(){const seq=Array.from({length:round+2},()=>Math.floor(Math.random()*3)),pads=['🥁','👏','🔔'];let input=[];play.innerHTML=`<div><p>Escucha la secuencia y repítela.</p><div class="pads">${pads.map((p,i)=>`<button class="pad" type="button" data-pad="${i}" aria-label="Sonido ${i+1}">${p}</button>`).join('')}</div></div>`;const btns=[...play.querySelectorAll('[data-pad]')];const flash=(idx,delay)=>setTimeout(()=>{btns[idx].classList.add('flash');setTimeout(()=>btns[idx].classList.remove('flash'),260)},delay);seq.forEach((n,i)=>flash(n,350+i*520));btns.forEach(b=>b.onclick=()=>{input.push(Number(b.dataset.pad));const k=input.length-1;if(input[k]!==seq[k]){input=[];feedback.textContent='Escucha otra vez.';seq.forEach((n,i)=>flash(n,300+i*520));return}if(input.length===seq.length)finish(true,'¡Ritmo perfecto!')})}
function followPath(){const path=['🐇','🌼','🪨','🥕'];let next=0;play.innerHTML=`<div><p>Sigue el camino en orden hasta la zanahoria.</p><div class="choices">${path.map((x,i)=>`<button class="choice" type="button" data-step="${i}" aria-label="Paso ${i+1}">${x}</button>`).join('')}</div></div>`;play.querySelectorAll('[data-step]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.step);if(i!==next){feedback.textContent='Vuelve al último punto del camino.';return}b.disabled=true;b.setAttribute('aria-pressed','true');next++;if(next===path.length)finish(true,'¡Llegaste siguiendo el camino!')})}
function colorSort(){const items=[['🍎','rojo'],['🚗','rojo'],['🐸','verde'],['🍐','verde']];let selected=null,done=0;play.innerHTML=`<div><p>Clasifica cada objeto por color.</p><div class="choices">${items.map((x,i)=>`<button class="choice" type="button" data-item="${i}" data-color="${x[1]}">${x[0]}</button>`).join('')}</div><div class="choices"><button class="choice" data-bin="rojo" type="button">Caja roja</button><button class="choice" data-bin="verde" type="button">Caja verde</button></div></div>`;play.querySelectorAll('[data-item]').forEach(b=>b.onclick=()=>{selected=b;play.querySelectorAll('[data-item]').forEach(x=>x.removeAttribute('aria-pressed'));b.setAttribute('aria-pressed','true')});play.querySelectorAll('[data-bin]').forEach(bin=>bin.onclick=()=>{if(!selected){feedback.textContent='Elige primero un objeto.';return}if(selected.dataset.color!==bin.dataset.bin){feedback.textContent='Mira el color de nuevo.';return}selected.disabled=true;selected.removeAttribute('aria-pressed');selected=null;done++;if(done===items.length)finish(true,'¡Todo está bien clasificado!')})}
function jigsaw(){const pieces=[0,1,2,3].sort(()=>Math.random()-.5);let next=0;play.innerHTML=`<div><p>Reconstruye el paisaje colocando las piezas 1, 2, 3 y 4.</p><div class="choices">${pieces.map(i=>`<button class="choice" type="button" data-piece="${i}">Pieza ${i+1}</button>`).join('')}</div><div data-board aria-live="polite"></div></div>`;const board=play.querySelector('[data-board]');play.querySelectorAll('[data-piece]').forEach(b=>b.onclick=()=>{const i=Number(b.dataset.piece);if(i!==next){feedback.textContent='Busca la pieza que continúa la imagen.';return}board.textContent+=['🌲','🏞️','🌳','☀️'][i];b.disabled=true;next++;if(next===4)finish(true,'¡Puzzle completo!')})}
function maze(){const cells=9,blocked=new Set([1,5]),goal=8;let pos=0;play.innerHTML='<div><p>Lleva a Lío hasta la estrella sin pasar por las rocas.</p><div data-maze style="display:grid;grid-template-columns:repeat(3,70px);gap:6px;justify-content:center"></div><div class="choices"><button class="choice" data-move="-3">↑</button><button class="choice" data-move="-1">←</button><button class="choice" data-move="1">→</button><button class="choice" data-move="3">↓</button></div></div>';const board=play.querySelector('[data-maze]');const draw=()=>{board.innerHTML='';for(let i=0;i<cells;i++){const d=document.createElement('div');d.style='height:70px;border-radius:14px;background:#eee9ff;display:grid;place-items:center;font-size:30px';d.textContent=i===pos?'🦁':i===goal?'⭐':blocked.has(i)?'🪨':'';board.appendChild(d)}};draw();play.querySelectorAll('[data-move]').forEach(b=>b.onclick=()=>{const delta=Number(b.dataset.move),n=pos+delta;if(n<0||n>=cells||blocked.has(n)||(delta===1&&pos%3===2)||(delta===-1&&pos%3===0)){feedback.textContent='Ese camino está bloqueado.';return}pos=n;draw();if(pos===goal)finish(true,'¡Encontraste la salida!')})}
function dayOrder(){const steps=[['🌅','Despertarse'],['🥣','Desayunar'],['🪥','Lavarse los dientes'],['🎒','Ir al cole']];const shuffled=[...steps].sort(()=>Math.random()-.5);let next=0;play.innerHTML=`<div><p>Ordena la mañana paso a paso.</p><div class="choices">${shuffled.map(x=>`<button class="choice" type="button" data-order="${steps.findIndex(s=>s[1]===x[1])}">${x[0]} ${x[1]}</button>`).join('')}</div></div>`;play.querySelectorAll('[data-order]').forEach(b=>b.onclick=()=>{if(Number(b.dataset.order)!==next){feedback.textContent='Piensa qué ocurre antes.';return}b.disabled=true;next++;if(next===steps.length)finish(true,'¡Rutina ordenada!')})}
function differences(){const target=round%3;const pairs=[['🌳🌼🐞','🌳🌻🐞'],['🚗🏠☁️','🚙🏠☁️'],['🐟🌊⭐','🐟🌊🌙']];const [a,b]=pairs[target];play.innerHTML=`<div><p>Encuentra qué cambia entre las dos escenas.</p><div style="display:flex;gap:18px;font-size:42px;justify-content:center"><span>${a}</span><span>${b}</span></div><div class="choices"><button class="choice" data-diff="0">Primer elemento</button><button class="choice" data-diff="1">Elemento central</button><button class="choice" data-diff="2">Último elemento</button></div></div>`;const correct=[1,0,2][target];play.querySelectorAll('[data-diff]').forEach(btn=>btn.onclick=()=>Number(btn.dataset.diff)===correct?finish(true,'¡Detectaste la diferencia!'):(feedback.textContent='Compara las dos escenas otra vez.'))}
const handlers={'luces-y-sonidos':tapCause,'encaja-grande':fitShape,'torre-de-mimo':tower,'parejas-sonoras':soundPairs,'busca-en-la-casa':hiddenObject,'ritmo-de-pipa':rhythm,'camino-del-conejo':followPath,'cajas-de-colores':colorSort,'puzzle-del-bosque':jigsaw,'laberinto-de-lio':maze,'ordenamos-el-dia':dayOrder,'detectives-de-diferencias':differences};
$('closeGame').onclick=()=>{clear();stage.hidden=true;current=null};
const saved=read();if(saved.age&&P.ageBands.some(b=>b.id===saved.age))age=saved.age;renderAges();renderGames();
globalThis.MundoMimoV2Runtime=Object.freeze({version:200,implemented:Object.freeze([...IMPLEMENTED]),handlers:Object.freeze(Object.keys(handlers)),stateKey,start});
})();
