(()=>{'use strict';
if(globalThis.MundoMimoV2)return;
const VERSION=200;
const AGE_BANDS=Object.freeze([
{id:'0-1',min:0,max:1,label:'0–1 años',focus:['causa-efecto','atencion-conjunta','percepcion','coordinacion']},
{id:'1-2',min:1,max:2,label:'1–2 años',focus:['lenguaje-receptivo','imitacion','clasificacion-simple','motricidad']},
{id:'2-3',min:2,max:3,label:'2–3 años',focus:['vocabulario','conteo-inicial','categorias','emociones']},
{id:'3-4',min:3,max:4,label:'3–4 años',focus:['conciencia-fonologica','cantidad','patrones','memoria']},
{id:'4-5',min:4,max:5,label:'4–5 años',focus:['prelectura','numeracion','logica','secuencias']},
{id:'5-6',min:5,max:6,label:'5–6 años',focus:['lectoescritura-inicial','problemas','funciones-ejecutivas','creatividad']}
]);
const AREAS=Object.freeze(['lenguaje','conciencia-fonologica','prelectura','lectoescritura','matematicas','geometria','logica','memoria','atencion','funciones-ejecutivas','ciencia','mundo-cotidiano','musica','emociones','habilidades-sociales','autonomia','creatividad','psicomotricidad']);
const MECHANICS=Object.freeze([
{ id:'tap-target',family:'touch'},{id:'hold-release',family:'touch'},{id:'drag-target',family:'drag'},{id:'drag-zones',family:'drag'},{id:'sort-order',family:'sequence'},{id:'fit-shape',family:'construction'},{id:'category-sort',family:'classification'},{id:'pair-match',family:'matching'},{id:'connect-pairs',family:'matching'},{id:'free-draw',family:'creation'},{id:'guided-trace',family:'motor'},{id:'follow-path',family:'motor'},{id:'jigsaw',family:'puzzle'},{id:'maze',family:'navigation'},{id:'memory-cards',family:'memory'},{id:'spot-difference',family:'attention'},{id:'hidden-object',family:'attention'},{id:'odd-one-out',family:'attention'},{id:'sequence-complete',family:'sequence'},{id:'pattern-rule',family:'logic'},{id:'fill-missing',family:'completion'},{id:'block-build',family:'construction'},{id:'story-order',family:'narrative'},{id:'listen-choose',family:'audio'},{id:'rhythm-repeat',family:'audio'},{id:'sequence-imitate',family:'memory'},{id:'cause-effect',family:'exploration'},{id:'simple-simulation',family:'science'},{id:'free-explore',family:'exploration'},{id:'color-fill',family:'creation'},{id:'music-compose',family:'creation'},{id:'sound-recognition',family:'audio'},{id:'visual-recognition',family:'perception'},{id:'semantic-association',family:'matching'},{id:'logic-grid',family:'logic'},{id:'multi-select',family:'choice'},{id:'context-choice',family:'choice'},{id:'step-order',family:'sequence'},{id:'consequence-choice',family:'social'},{id:'geometry-build',family:'construction'},{id:'multi-attribute-sort',family:'classification'},{id:'symbolic-play',family:'simulation'},{id:'interactive-story',family:'narrative'},{id:'narrative-puzzle',family:'puzzle'},{id:'problem-solve',family:'logic'},{id:'experiment',family:'science'},{id:'auditory-memory',family:'memory'},{id:'spatial-navigation',family:'navigation'},{id:'multi-instruction',family:'executive'},{id:'age-safe-reaction',family:'attention'}
]);
const mechanicIds=Object.freeze(MECHANICS.map(x=>x.id));
const GAME_SCHEMA=Object.freeze(['id','name','ages','area','skill','subskill','mechanic','objective','rules','levels','feedback','hints','accessibility']);
function validateGame(game){const errors=[];for(const key of GAME_SCHEMA)if(game?.[key]==null||game[key]==='')errors.push(`missing:${key}`);if(game?.id&&!/^[a-z0-9-]+$/.test(game.id))errors.push('invalid:id');if(game?.ages&&!Array.isArray(game.ages))errors.push('invalid:ages');if(Array.isArray(game?.ages)&&game.ages.some(a=>!AGE_BANDS.some(b=>b.id===a)))errors.push('invalid:age-band');if(game?.area&&!AREAS.includes(game.area))errors.push('invalid:area');if(game?.mechanic&&!mechanicIds.includes(game.mechanic))errors.push('invalid:mechanic');if(game?.levels&&!Number.isInteger(game.levels))errors.push('invalid:levels');return errors;}
function validateCatalog(games){const errors=[];if(!Array.isArray(games))return ['catalog:not-array'];const ids=games.map(g=>g.id);if(new Set(ids).size!==ids.length)errors.push('catalog:duplicate-game-id');for(const g of games)for(const e of validateGame(g))errors.push(`${g?.id||'unknown'}:${e}`);return errors;}
function distinctGameSignature(game){return [game.mechanic,game.objective,game.rules?.interaction,game.rules?.win,game.rules?.progression].join('|');}
function cloneGroups(games){const groups=new Map();for(const g of games){const s=distinctGameSignature(g);const list=groups.get(s)||[];list.push(g.id);groups.set(s,list);}return [...groups.values()].filter(x=>x.length>1);}
function metrics(games=[],activities=0,levels=0,challenges=0,variants=0){return Object.freeze({mechanics:MECHANICS.length,games:games.length,activities,levels,challenges,variants,areas:AREAS.length,skills:new Set(games.map(g=>g.skill)).size,ageBands:AGE_BANDS.length,cloneGroups:cloneGroups(games).length});}
globalThis.MundoMimoV2=Object.freeze({version:VERSION,ageBands:AGE_BANDS,areas:AREAS,mechanics:MECHANICS,mechanicIds,GAME_SCHEMA,validateGame,validateCatalog,distinctGameSignature,cloneGroups,metrics});
})();
