const {test,expect}=require('@playwright/test');
async function boot(page){await page.goto('/v2/app-v200.html');await page.waitForFunction(()=>Boolean(window.MundoMimoV2RuntimeV360));}
test('v360 exposes 108 implemented games with unique handlers and no clones',async({page})=>{await boot(page);const r=await page.evaluate(()=>{const x=window.MundoMimoV2RuntimeV360,E=window.MundoMimoV2ExpansionV360;return{implemented:x.implemented,handlers:x.handlers,errors:E.errors,clones:E.cloneGroups}});expect(r.errors).toEqual([]);expect(r.clones).toEqual([]);expect(r.implemented).toHaveLength(108);expect(new Set(r.implemented).size).toBe(108);expect(new Set(r.handlers).size).toBe(108);});
test('shadow matching rejects wrong contour then accepts the matching silhouette',async({page})=>{await boot(page);await page.locator('[data-age="2-3"]').click();await page.locator('[data-game="busca-la-pareja-de-sombras"]').click();await page.locator('[data-shadow="ball"]').click();await expect(page.locator('#feedback')).toContainText('contorno');await page.locator('[data-shadow="umbrella"]').click();await expect(page.locator('#feedback')).toContainText('silueta');});
test('robot planning requires the exact instruction sequence',async({page})=>{await boot(page);await page.locator('[data-age="4-5"]').click();await page.locator('[data-game="pasos-del-robot"]').click();await page.locator('[data-step="arriba"]').click();await page.locator('[data-step="derecha"]').click();await page.locator('[data-check-robot]').click();await expect(page.locator('#feedback')).toContainText('no llega');await page.locator('[data-step="derecha"]').click();await page.locator('[data-step="arriba"]').click();await page.locator('[data-check-robot]').click();await expect(page.locator('#feedback')).toContainText('meta');});
test('float experiment records a prediction and verifies the material outcome',async({page})=>{await boot(page);await page.locator('[data-age="3-4"]').click();await page.locator('[data-game="que-flota-aqui"]').click();await page.locator('[data-float="hunde"]').click();await expect(page.locator('#feedback')).toContainText('material');await page.locator('[data-float="flota"]').click();await expect(page.locator('#feedback')).toContainText('Comprobado');});
test('rhyme game depends on the ending sound',async({page})=>{await boot(page);await page.locator('[data-age="4-5"]').click();await page.locator('[data-game="palabras-que-terminan-igual"]').click();await page.locator('[data-rhyme="mesa"]').click();await expect(page.locator('#feedback')).toContainText('final');await page.locator('[data-rhyme="pato"]').click();await expect(page.locator('#feedback')).toContainText('igual');});
test('backpack planning requires exactly the functional items',async({page})=>{await boot(page);await page.locator('[data-age="3-4"]').click();await page.locator('[data-game="prepara-la-mochila"]').click();await page.locator('[data-pack="toalla"]').click();await page.locator('[data-pack="cuchara"]').click();await page.locator('[data-check-pack]').click();await expect(page.locator('#feedback')).toContainText('realmente');await page.locator('[data-pack="cuchara"]').click();await page.locator('[data-pack="bañador"]').click();await page.locator('[data-check-pack]').click();await expect(page.locator('#feedback')).toContainText('necesario');});
test('symmetry completion rejects the same half and accepts the reflected half',async({page})=>{await boot(page);await page.locator('[data-age="4-5"]').click();await page.locator('[data-game="construye-la-mitad"]').click();await page.locator('[data-half="same"]').click();await expect(page.locator('#feedback')).toContainText('reflejada');await page.locator('[data-half="mirror"]').click();await expect(page.locator('#feedback')).toContainText('reflejo');});
test('advanced v360 games stay out of the 1-2 band',async({page})=>{await boot(page);await page.locator('[data-age="1-2"]').click();await expect(page.locator('[data-game="pasos-del-robot"]')).toHaveCount(0);await expect(page.locator('[data-game="palabras-que-terminan-igual"]')).toHaveCount(0);await expect(page.locator('[data-game="construye-la-mitad"]')).toHaveCount(0);});