const {test,expect}=require('@playwright/test');
async function boot(page){await page.goto('/v2/app-v200.html');await page.waitForFunction(()=>Boolean(window.MundoMimoV2RuntimeV340));}
test('v340 exposes 96 implemented games with unique handlers and no clones',async({page})=>{await boot(page);const r=await page.evaluate(()=>{const x=window.MundoMimoV2RuntimeV340,E=window.MundoMimoV2ExpansionV340;return{implemented:x.implemented,handlers:x.handlers,errors:E.errors,clones:E.cloneGroups}});expect(r.errors).toEqual([]);expect(r.clones).toEqual([]);expect(r.implemented).toHaveLength(96);expect(new Set(r.implemented).size).toBe(96);expect(new Set(r.handlers).size).toBe(96);});
test('plant sequence enforces natural causal order',async({page})=>{await boot(page);await page.locator('[data-age="2-3"]').click();await page.locator('[data-game="semillas-que-crecen"]').click();await page.locator('[data-plant="1"]').click();await page.locator('[data-plant="0"]').click();await page.locator('[data-plant="2"]').click();await page.locator('[data-check-plant]').click();await expect(page.locator('#feedback')).toContainText('primero');await page.locator('[data-plant="0"]').click();await page.locator('[data-plant="1"]').click();await page.locator('[data-plant="2"]').click();await page.locator('[data-check-plant]').click();await expect(page.locator('#feedback')).toContainText('Semilla');});
test('routine clock rejects action from wrong time of day',async({page})=>{await boot(page);await page.locator('[data-age="2-3"]').click();await page.locator('[data-game="reloj-de-rutinas"]').click();await page.locator('[data-routine="cenar"]').click();await expect(page.locator('#feedback')).toContainText('momento');await page.locator('[data-routine="desayunar"]').click();await expect(page.locator('#feedback')).toContainText('Rutina');});
test('syllable builder requires ordered recomposition',async({page})=>{await boot(page);await page.locator('[data-age="4-5"]').click();await page.locator('[data-game="palabras-en-trozos"]').click();await page.locator('[data-syllable="sa"]').click();await page.locator('[data-syllable="ca"]').click();await page.locator('[data-check-syllables]').click();await expect(page.locator('#feedback')).toContainText('otro orden');await page.locator('[data-syllable="ca"]').click();await page.locator('[data-syllable="sa"]').click();await page.locator('[data-check-syllables]').click();await expect(page.locator('#feedback')).toContainText('sílabas');});
test('rotated figures require direction-preserving equivalence',async({page})=>{await boot(page);await page.locator('[data-age="4-5"]').click();await page.locator('[data-game="figuras-que-giran"]').click();await page.locator('[data-rotate="🔻⬆️"]').click();await expect(page.locator('#feedback')).toContainText('dirección');await page.locator('[data-rotate="🔺⬆️"]').click();await expect(page.locator('#feedback')).toContainText('equivalente');});
test('social turn game reinforces prosocial turn-taking',async({page})=>{await boot(page);await page.locator('[data-age="3-4"]').click();await page.locator('[data-game="el-turno-es-de"]').click();await page.locator('[data-social="empujar"]').click();await expect(page.locator('#feedback')).toContainText('cuide');await page.locator('[data-social="esperar"]').click();await expect(page.locator('#feedback')).toContainText('turno');});
test('receptive language combines category and attribute',async({page})=>{await boot(page);await page.locator('[data-age="1-2"]').click();await page.locator('[data-game="escucha-y-encuentra"]').click();await page.locator('[data-listenfind="pelota"]').click();await expect(page.locator('#feedback')).toContainText('objeto');await page.locator('[data-listenfind="elefante"]').click();await expect(page.locator('#feedback')).toContainText('detalles');});
test('advanced syllable and mental rotation games stay out of toddler bands',async({page})=>{await boot(page);await page.locator('[data-age="1-2"]').click();await expect(page.locator('[data-game="palabras-en-trozos"]')).toHaveCount(0);await expect(page.locator('[data-game="figuras-que-giran"]')).toHaveCount(0);});