const {test,expect}=require('@playwright/test');
async function boot(page){await page.goto('/v2/app-v200.html');await page.waitForFunction(()=>Boolean(window.MundoMimoV2RuntimeV280));}

test('v280 exposes sixty implemented games without catalog clones',async({page})=>{await boot(page);const r=await page.evaluate(()=>{const x=window.MundoMimoV2RuntimeV280,E=window.MundoMimoV2ExpansionV280;return{implemented:x.implemented,handlers:x.handlers,games:x.allGames().map(g=>({id:g.id,mechanic:g.mechanic})),errors:E.errors,clones:E.cloneGroups}});expect(r.errors).toEqual([]);expect(r.clones).toEqual([]);expect(r.implemented).toHaveLength(60);expect(new Set(r.implemented).size).toBe(60);expect(new Set(r.handlers).size).toBe(60);expect(r.implemented.every(id=>r.games.some(g=>g.id===id))).toBeTruthy();});

test('body-sound game maps action to the appropriate body response',async({page})=>{await boot(page);await page.locator('[data-age="1-2"]').click();await page.locator('[data-game="sonidos-del-cuerpo"]').click();await page.locator('[data-body="👂"]').click();await expect(page.locator('#feedback')).toContainText('prueba');await page.locator('[data-body="👏"]').click();await expect(page.locator('#feedback')).toContainText('cuerpo');});

test('complement pairing rejects an incompatible match and accepts a valid pair',async({page})=>{await boot(page);await page.locator('[data-age="2-3"]').click();await page.locator('[data-game="mitades-que-encajan"]').click();await page.locator('[data-left="🍎"]').click();await page.locator('[data-right="🛞"]').click();await expect(page.locator('#feedback')).toContainText('no completan');await page.locator('[data-right="🍏"]').click();await expect(page.locator('#feedback')).toContainText('Encaja');});

test('shape route enforces both sequence and geometric rule',async({page})=>{await boot(page);await page.locator('[data-age="3-4"]').click();await page.locator('[data-game="ruta-de-formas"]').click();await page.locator('[data-cell="1"]').click();await expect(page.locator('#feedback')).toContainText('orden');await page.locator('[data-cell="0"]').click();await page.locator('[data-cell="2"]').click();await expect(page.locator('#feedback')).toContainText('meta');});

test('recipe planning requires causal ordering',async({page})=>{await boot(page);await page.locator('[data-age="4-5"]').click();await page.locator('[data-game="ordena-la-receta"]').click();await page.locator('[data-check-recipe]').click();await expect(page.locator('#feedback')).toContainText('Revisa');await page.locator('[data-step="Lavar"]').click();await page.locator('[data-step="Cortar"]').click();await page.locator('[data-step="Comer"]').click();await page.locator('[data-check-recipe]').click();await expect(page.locator('#feedback')).toContainText('segura');});

test('season garden tests prediction before simulated consequence',async({page})=>{await boot(page);await page.locator('[data-age="4-5"]').click();await page.locator('[data-game="jardin-de-estaciones"]').click();await page.locator('[data-season="🌸"]').click();await expect(page.locator('#feedback')).toContainText('clima');await page.locator('[data-season="❄️"]').click();await expect(page.locator('#feedback')).toContainText('predicción');});

test('syllable detective requires exactly the matching syllable set',async({page})=>{await boot(page);await page.locator('[data-age="5-6"]').click();await page.locator('[data-game="detective-de-silabas"]').click();await page.locator('[data-word="sol"]').click();await page.locator('[data-check-syllables]').click();await expect(page.locator('#feedback')).toContainText('palmadas');await page.locator('[data-word="sol"]').click();await page.locator('[data-word="mesa"]').click();await page.locator('[data-word="gato"]').click();await page.locator('[data-check-syllables]').click();await expect(page.locator('#feedback')).toContainText('sílabas');});

test('older phonological game is absent from toddler bands',async({page})=>{await boot(page);await page.locator('[data-age="1-2"]').click();await expect(page.locator('[data-game="detective-de-silabas"]')).toHaveCount(0);});