const {test,expect}=require('@playwright/test');
async function boot(page){await page.goto('/v2/app-v200.html');await page.waitForFunction(()=>Boolean(window.MundoMimoV2RuntimeV330));}
test('v330 exposes 90 implemented games with unique handlers and no clones',async({page})=>{await boot(page);const r=await page.evaluate(()=>{const x=window.MundoMimoV2RuntimeV330,E=window.MundoMimoV2ExpansionV330;return{implemented:x.implemented,handlers:x.handlers,errors:E.errors,clones:E.cloneGroups}});expect(r.errors).toEqual([]);expect(r.clones).toEqual([]);expect(r.implemented).toHaveLength(90);expect(new Set(r.implemented).size).toBe(90);expect(new Set(r.handlers).size).toBe(90);});
test('face imitation distinguishes expressions',async({page})=>{await boot(page);await page.locator('[data-age="1-2"]').click();await page.locator('[data-game="imita-la-cara"]').click();await page.locator('[data-face="triste"]').click();await expect(page.locator('#feedback')).toContainText('ojos');await page.locator('[data-face="feliz"]').click();await expect(page.locator('#feedback')).toContainText('mismo gesto');});
test('spatial language requires the shown relation',async({page})=>{await boot(page);await page.locator('[data-age="2-3"]').click();await page.locator('[data-game="donde-esta-mimo"]').click();await page.locator('[data-space="debajo"]').click();await expect(page.locator('#feedback')).toContainText('posición');await page.locator('[data-space="encima"]').click();await expect(page.locator('#feedback')).toContainText('dónde');});
test('movement mission preserves instruction order',async({page})=>{await boot(page);await page.locator('[data-age="3-4"]').click();await page.locator('[data-game="mision-de-movimientos"]').click();await page.locator('[data-move="🙌"]').click();await expect(page.locator('#feedback')).toContainText('orden');await page.locator('[data-move="👏"]').click();await page.locator('[data-move="🙌"]').click();await expect(page.locator('#feedback')).toContainText('pasos');});
test('same-initial game requires the complete phonological set',async({page})=>{await boot(page);await page.locator('[data-age="4-5"]').click();await page.locator('[data-game="empiezan-igual"]').click();await page.locator('[data-word="mano"]').click();await page.locator('[data-check-initial]').click();await expect(page.locator('#feedback')).toContainText('Falta');await page.locator('[data-word="mesa"]').click();await page.locator('[data-check-initial]').click();await expect(page.locator('#feedback')).toContainText('mismo sonido');});
test('make ten rejects non-ten pair and accepts exact decomposition',async({page})=>{await boot(page);await page.locator('[data-age="5-6"]').click();await page.locator('[data-game="haz-diez"]').click();await page.locator('[data-ten="1"]').click();await expect(page.locator('#feedback')).toContainText('suman');await page.locator('[data-ten="0"]').click();await expect(page.locator('#feedback')).toContainText('diez');});
test('color mixing compares prediction with simulated result',async({page})=>{await boot(page);await page.locator('[data-age="3-4"]').click();await page.locator('[data-game="laboratorio-de-mezclas"]').click();await page.locator('[data-mix="verde"]').click();await expect(page.locator('[data-mix-result]')).toContainText('🟠');await expect(page.locator('#feedback')).toContainText('otro color');await page.locator('[data-mix="naranja"]').click();await expect(page.locator('#feedback')).toContainText('comprobada');});
test('advanced phonology and ten decomposition stay out of toddler bands',async({page})=>{await boot(page);await page.locator('[data-age="1-2"]').click();await expect(page.locator('[data-game="empiezan-igual"]')).toHaveCount(0);await expect(page.locator('[data-game="haz-diez"]')).toHaveCount(0);});