const {test,expect}=require('@playwright/test');
async function boot(page){await page.goto('/v2/app-v200.html');await page.waitForFunction(()=>Boolean(window.MundoMimoV2RuntimeV350));}
test('v350 exposes 102 implemented games with unique handlers and no clones',async({page})=>{await boot(page);const r=await page.evaluate(()=>{const x=window.MundoMimoV2RuntimeV350,E=window.MundoMimoV2ExpansionV350;return{implemented:x.implemented,handlers:x.handlers,errors:E.errors,clones:E.cloneGroups}});expect(r.errors).toEqual([]);expect(r.clones).toEqual([]);expect(r.implemented).toHaveLength(102);expect(new Set(r.implemented).size).toBe(102);expect(new Set(r.handlers).size).toBe(102);});
test('sound source rejects unrelated source then accepts correct source',async({page})=>{await boot(page);await page.locator('[data-age="1-2"]').click();await page.locator('[data-game="quien-hace-ese-sonido"]').click();await page.locator('[data-source="coche"]').click();await expect(page.locator('#feedback')).toContainText('produce');await page.locator('[data-source="gato"]').click();await expect(page.locator('#feedback')).toContainText('sonido');});
test('length race requires strict shortest-to-longest order',async({page})=>{await boot(page);await page.locator('[data-age="3-4"]').click();await page.locator('[data-game="carrera-de-longitudes"]').click();await page.locator('[data-length="3"]').click();await page.locator('[data-length="1"]').click();await page.locator('[data-length="2"]').click();await page.locator('[data-check-length]').click();await expect(page.locator('#feedback')).toContainText('corto');await page.locator('[data-length="1"]').click();await page.locator('[data-length="2"]').click();await page.locator('[data-length="3"]').click();await page.locator('[data-check-length]').click();await expect(page.locator('#feedback')).toContainText('largo');});
test('tracks game uses visual clue rather than category guessing',async({page})=>{await boot(page);await page.locator('[data-age="2-3"]').click();await page.locator('[data-game="huellas-y-animales"]').click();await page.locator('[data-track="pez"]').click();await expect(page.locator('#feedback')).toContainText('huella');await page.locator('[data-track="perro"]').click();await expect(page.locator('#feedback')).toContainText('encaja');});
test('body signal maps contextual sensation to emotion',async({page})=>{await boot(page);await page.locator('[data-age="3-4"]').click();await page.locator('[data-game="mi-cuerpo-me-avisa"]').click();await page.locator('[data-body="alegria"]').click();await expect(page.locator('#feedback')).toContainText('situación');await page.locator('[data-body="nervios"]').click();await expect(page.locator('#feedback')).toContainText('cuerpo');});
test('fair share requires equal one-to-one distribution',async({page})=>{await boot(page);await page.locator('[data-age="3-4"]').click();await page.locator('[data-game="reparte-el-camino"]').click();for(let i=0;i<4;i++)await page.locator('[data-share="a"]').click();await expect(page.locator('#feedback')).toContainText('misma cantidad');await page.waitForTimeout(300);for(let i=0;i<2;i++){await page.locator('[data-share="a"]').click();await page.locator('[data-share="b"]').click();}await expect(page.locator('#feedback')).toContainText('justo');});
test('before-after story requires causal temporal sequence',async({page})=>{await boot(page);await page.locator('[data-age="3-4"]').click();await page.locator('[data-game="antes-o-despues"]').click();await page.locator('[data-time="lavar"]').click();await page.locator('[data-time="abrir"]').click();await page.locator('[data-time="secar"]').click();await page.locator('[data-check-time]').click();await expect(page.locator('#feedback')).toContainText('primero');await page.locator('[data-time="abrir"]').click();await page.locator('[data-time="lavar"]').click();await page.locator('[data-time="secar"]').click();await page.locator('[data-check-time]').click();await expect(page.locator('#feedback')).toContainText('principio');});
test('older measurement and emotional games stay out of 1-2 band',async({page})=>{await boot(page);await page.locator('[data-age="1-2"]').click();await expect(page.locator('[data-game="carrera-de-longitudes"]')).toHaveCount(0);await expect(page.locator('[data-game="mi-cuerpo-me-avisa"]')).toHaveCount(0);});