const {test,expect}=require('@playwright/test');
async function boot(page){await page.goto('/v2/app-v200.html');await page.waitForFunction(()=>Boolean(window.MundoMimoV2RuntimeV320));}
test('v320 exposes 84 implemented games with unique handlers and no clones',async({page})=>{await boot(page);const r=await page.evaluate(()=>{const x=window.MundoMimoV2RuntimeV320,E=window.MundoMimoV2ExpansionV320;return{implemented:x.implemented,handlers:x.handlers,errors:E.errors,clones:E.cloneGroups}});expect(r.errors).toEqual([]);expect(r.clones).toEqual([]);expect(r.implemented).toHaveLength(84);expect(new Set(r.implemented).size).toBe(84);expect(new Set(r.handlers).size).toBe(84);});
test('guided breathing requires waiting for release cue',async({page})=>{await boot(page);await page.locator('[data-age="2-3"]').click();await page.locator('[data-game="respira-con-mimo"]').click();const b=page.locator('[data-breathe]');await b.dispatchEvent('pointerdown');await b.dispatchEvent('pointerup');await expect(page.locator('#feedback')).toContainText('Espera');await b.dispatchEvent('pointerdown');await page.waitForTimeout(420);await b.dispatchEvent('pointerup');await expect(page.locator('#feedback')).toContainText('pausa');});
test('recycling game classifies material instead of accepting any bin',async({page})=>{await boot(page);await page.locator('[data-age="3-4"]').click();await page.locator('[data-game="patrulla-del-reciclaje"]').click();await page.locator('[data-bin="envases"]').click();await expect(page.locator('#feedback')).toContainText('material');await page.locator('[data-bin="papel"]').click();await expect(page.locator('#feedback')).toContainText('correcta');});
test('silhouette matching rejects wrong object and accepts contour match',async({page})=>{await boot(page);await page.locator('[data-age="2-3"]').click();await page.locator('[data-game="siluetas-del-taller"]').click();await page.locator('[data-sil="libro"]').click();await expect(page.locator('#feedback')).toContainText('contorno');await page.locator('[data-sil="pelota"]').click();await expect(page.locator('#feedback')).toContainText('forma');});
test('garden sums require exact composition',async({page})=>{await boot(page);await page.locator('[data-age="4-5"]').click();await page.locator('[data-game="jardin-de-sumas"]').click();await page.locator('[data-pair="2"]').click();await expect(page.locator('#feedback')).toContainText('juntas');await page.locator('[data-pair="0"]').click();await expect(page.locator('#feedback')).toContainText('floreció');});
test('auditory memory preserves sequence order',async({page})=>{await boot(page);await page.locator('[data-age="3-4"]').click();await page.locator('[data-game="eco-de-sonidos"]').click();await page.locator('[data-sound="🥁"]').click();await expect(page.locator('#feedback')).toContainText('orden');await page.locator('[data-sound="🔔"]').click();await page.locator('[data-sound="🥁"]').click();await expect(page.locator('#feedback')).toContainText('secuencia');});
test('profession association links need to function',async({page})=>{await boot(page);await page.locator('[data-age="3-4"]').click();await page.locator('[data-game="quien-nos-ayuda"]').click();await page.locator('[data-helper="panadera"]').click();await expect(page.locator('#feedback')).toContainText('tarea');await page.locator('[data-helper="bombero"]').click();await expect(page.locator('#feedback')).toContainText('profesión');});
test('advanced v320 maths stays out of toddler bands',async({page})=>{await boot(page);await page.locator('[data-age="1-2"]').click();await expect(page.locator('[data-game="jardin-de-sumas"]')).toHaveCount(0);await expect(page.locator('[data-game="eco-de-sonidos"]')).toHaveCount(0);});