const {test,expect}=require('@playwright/test');
async function boot(page){await page.goto('/v2/app-v200.html');await page.waitForFunction(()=>Boolean(window.MundoMimoV2RuntimeV430));}
test('v430 exposes 150 implemented games with unique handlers and no clones',async({page})=>{await boot(page);const r=await page.evaluate(()=>{const x=window.MundoMimoV2RuntimeV430,E=window.MundoMimoV2ExpansionV430;return{implemented:x.implemented,handlers:x.handlers,errors:E.errors,clones:E.cloneGroups}});expect(r.errors).toEqual([]);expect(r.clones).toEqual([]);expect(r.implemented).toHaveLength(150);expect(new Set(r.implemented).size).toBe(150);expect(new Set(r.handlers).size).toBe(150);});
test('gesture echo rejects wrong gesture and accepts model',async({page})=>{await boot(page);await page.locator('[data-age="0-1"]').click();await page.locator('[data-game="eco-de-gestos"]').click();await page.locator('[data-gesture="sentado"]').click();await expect(page.locator('#feedback')).toContainText('Mira');await page.locator('[data-gesture="manos-arriba"]').click();await expect(page.locator('#feedback')).toContainText('coincide');});
test('sound box links familiar sound and object',async({page})=>{await boot(page);await page.locator('[data-age="1-2"]').click();await page.locator('[data-game="caja-de-sonidos"]').click();await page.locator('[data-sound-box="vaso"]').click();await expect(page.locator('#feedback')).toContainText('Escucha');await page.locator('[data-sound-box="telefono"]').click();await expect(page.locator('#feedback')).toContainText('sonido');});
test('equal towers enforce exact quantity',async({page})=>{await boot(page);await page.locator('[data-age="2-3"]').click();await page.locator('[data-game="torres-iguales"]').click();await page.locator('[data-add-block]').click();await expect(page.locator('[data-tower-count]')).toHaveText('1');await page.locator('[data-add-block]').click();await expect(page.locator('#feedback')).toContainText('misma cantidad');});
test('word picture maps word to exact image',async({page})=>{await boot(page);await page.locator('[data-age="3-4"]').click();await page.locator('[data-game="palabra-y-dibujo"]').click();await page.locator('[data-word-picture="🐟"]').click();await expect(page.locator('#feedback')).toContainText('no representa');await page.locator('[data-word-picture="☀️"]').click();await expect(page.locator('#feedback')).toContainText('coinciden');});
test('rule path resets on forbidden cell and completes planned route',async({page})=>{await boot(page);await page.locator('[data-age="4-5"]').click();await page.locator('[data-game="camino-con-reglas"]').click();await page.locator('[data-rule-step="X"]').click();await expect(page.locator('#feedback')).toContainText('prohibida');for(const x of ['A','B','C'])await page.locator(`[data-rule-step="${x}"]`).click();await expect(page.locator('#feedback')).toContainText('respetando');});
test('cause detective rejects explanation without evidence and accepts causal inference',async({page})=>{await boot(page);await page.locator('[data-age="5-6"]').click();await page.locator('[data-game="detective-de-causas"]').click();await page.locator('[data-cause="hizo-mucho-sol"]').click();await expect(page.locator('#feedback')).toContainText('evidencia');await page.locator('[data-cause="llovio"]').click();await expect(page.locator('#feedback')).toContainText('causa');});
test('advanced v430 games stay out of early bands',async({page})=>{await boot(page);await page.locator('[data-age="0-1"]').click();for(const id of ['palabra-y-dibujo','camino-con-reglas','detective-de-causas'])await expect(page.locator(`[data-game="${id}"]`)).toHaveCount(0);});