const {test,expect}=require('@playwright/test');
async function boot(page){await page.goto('/v2/app-v200.html');await page.waitForFunction(()=>Boolean(window.MundoMimoV2RuntimeV290));}

test('v290 exposes sixty-six implemented games without catalog clones',async({page})=>{await boot(page);const r=await page.evaluate(()=>{const x=window.MundoMimoV2RuntimeV290,E=window.MundoMimoV2ExpansionV290;return{implemented:x.implemented,handlers:x.handlers,games:x.allGames().map(g=>({id:g.id,mechanic:g.mechanic})),errors:E.errors,clones:E.cloneGroups}});expect(r.errors).toEqual([]);expect(r.clones).toEqual([]);expect(r.implemented).toHaveLength(66);expect(new Set(r.implemented).size).toBe(66);expect(new Set(r.handlers).size).toBe(66);expect(r.implemented.every(id=>r.games.some(g=>g.id===id))).toBeTruthy();});

test('wait-and-discover rejects early release and accepts release after signal',async({page})=>{await boot(page);await page.locator('[data-age="1-2"]').click();await page.locator('[data-game="espera-y-descubre"]').click();const b=page.locator('[data-wait]');await b.dispatchEvent('pointerdown');await b.dispatchEvent('pointerup');await expect(page.locator('#feedback')).toContainText('Espera');await b.dispatchEvent('pointerdown');await page.waitForTimeout(320);await expect(page.locator('[data-signal]')).toContainText('⭐');await b.dispatchEvent('pointerup');await expect(page.locator('#feedback')).toContainText('señal');});

test('size staircase requires strict ascending order',async({page})=>{await boot(page);await page.locator('[data-age="2-3"]').click();await page.locator('[data-game="escalera-de-tamanos"]').click();await page.locator('[data-size="3"]').click();await expect(page.locator('#feedback')).toContainText('pequeño');await page.locator('[data-size="1"]').click();await page.locator('[data-size="2"]').click();await page.locator('[data-size="3"]').click();await expect(page.locator('#feedback')).toContainText('tamaños');});

test('emotion-cause matching rejects incoherent cause and accepts coherent pair',async({page})=>{await boot(page);await page.locator('[data-age="3-4"]').click();await page.locator('[data-game="une-emocion-y-motivo"]').click();await page.locator('[data-sit="Se rompió su juguete"]').click();await page.locator('[data-emo="😊"]').click();await expect(page.locator('#feedback')).toContainText('sentiría');await page.locator('[data-emo="😢"]').click();await page.locator('[data-sit="Le dieron un abrazo"]').click();await page.locator('[data-emo="😊"]').click();await expect(page.locator('#feedback')).toContainText('emociones');});

test('sentence completion requires semantic and grammatical coherence',async({page})=>{await boot(page);await page.locator('[data-age="4-5"]').click();await page.locator('[data-game="completa-la-frase"]').click();await page.locator('[data-word="nada"]').click();await expect(page.locator('#feedback')).toContainText('frase');await page.locator('[data-word="vuela"]').click();await expect(page.locator('#feedback')).toContainText('sentido');});

test('quantity balance requires exact two-part equivalence',async({page})=>{await boot(page);await page.locator('[data-age="4-5"]').click();await page.locator('[data-game="balanza-de-cantidades"]').click();await page.locator('[data-n="4"]').click();await page.locator('[data-n="3"]').click();await page.locator('[data-check-balance]').click();await expect(page.locator('#feedback')).toContainText('exactamente 5');await page.locator('[data-n="4"]').click();await page.locator('[data-n="2"]').click();await page.locator('[data-check-balance]').click();await expect(page.locator('#feedback')).toContainText('equilibrada');});

test('arrow code hides model before reproduction and enforces exact order',async({page})=>{await boot(page);await page.locator('[data-age="5-6"]').click();await page.locator('[data-game="codigo-de-flechas"]').click();await page.locator('[data-hide-code]').click();await expect(page.locator('[data-code]')).toBeHidden();await page.locator('[data-arrow="➡️"]').click();await expect(page.locator('#feedback')).toContainText('orden');await page.locator('[data-arrow="⬆️"]').click();await page.locator('[data-arrow="➡️"]').click();await page.locator('[data-arrow="⬇️"]').click();await expect(page.locator('#feedback')).toContainText('código');});

test('advanced arrow-code game is absent from early developmental bands',async({page})=>{await boot(page);await page.locator('[data-age="1-2"]').click();await expect(page.locator('[data-game="codigo-de-flechas"]')).toHaveCount(0);});