const {test,expect}=require('@playwright/test');
async function boot(page){await page.goto('/v2/app-v200.html');await page.waitForFunction(()=>Boolean(window.MundoMimoV2RuntimeV270));}

test('v270 exposes fifty-four implemented games with honest catalog metrics',async({page})=>{await boot(page);const r=await page.evaluate(()=>{const x=window.MundoMimoV2RuntimeV270;return{implemented:x.implemented,handlers:x.handlers,games:x.allGames().map(g=>({id:g.id,mechanic:g.mechanic})),errors:window.MundoMimoV2ExpansionV270.errors,clones:window.MundoMimoV2ExpansionV270.cloneGroups}});expect(r.errors).toEqual([]);expect(r.clones).toEqual([]);expect(r.implemented).toHaveLength(54);expect(new Set(r.implemented).size).toBe(54);expect(new Set(r.handlers).size).toBe(54);expect(r.implemented.every(id=>r.games.some(g=>g.id===id))).toBeTruthy();});

test('magnitude ordering requires a complete ordered sequence',async({page})=>{await boot(page);await page.locator('[data-age="3-4"]').click();await page.locator('[data-game="de-menor-a-mayor"]').click();await page.locator('[data-check]').click();await expect(page.locator('#feedback')).toContainText('vuelve a ordenar');const items=page.locator('[data-sort]');await items.nth(2).click();await items.nth(1).click();await items.nth(0).click();await page.locator('[data-check]').click();await expect(page.locator('#feedback')).toContainText('magnitud');});

test('animal families rejects a wrong biological pairing and accepts the correct one',async({page})=>{await boot(page);await page.locator('[data-age="2-3"]').click();await page.locator('[data-game="familias-de-animales"]').click();await page.locator('[data-adult="🐔"]').click();await page.locator('[data-baby="🐮"]').click();await expect(page.locator('#feedback')).toContainText('no corresponde');await page.locator('[data-baby="🐣"]').click();await expect(page.locator('#feedback')).toContainText('Familia');});

test('emotion drawing requires actual graphical interaction',async({page})=>{await boot(page);await page.locator('[data-age="4-5"]').click();await page.locator('[data-game="dibuja-como-te-sientes"]').click();await page.locator('[data-done]').click();await expect(page.locator('#feedback')).toContainText('Añade');const c=page.locator('[data-canvas]');await c.click({position:{x:30,y:30}});await c.click({position:{x:60,y:60}});await c.click({position:{x:90,y:90}});await page.locator('[data-done]').click();await expect(page.locator('#feedback')).toContainText('emoción');});

test('instrument recognition distinguishes timbre cues',async({page})=>{await boot(page);await page.locator('[data-age="3-4"]').click();await page.locator('[data-game="que-instrumento-suena"]').click();await page.locator('[data-inst="Flauta"]').click();await expect(page.locator('#feedback')).toContainText('compara');await page.locator('[data-inst="Tambor"]').click();await expect(page.locator('#feedback')).toContainText('instrumento');});

test('logic houses has a uniquely solvable first round',async({page})=>{await boot(page);await page.locator('[data-age="4-5"]').click();await page.locator('[data-game="casitas-logicas"]').click();await page.locator('[data-house="roja"]').click();await expect(page.locator('#feedback')).toContainText('contradice');await page.locator('[data-house="verde"]').click();await expect(page.locator('#feedback')).toContainText('pistas lógicas');});

test('autonomy context choice selects a functional solution',async({page})=>{await boot(page);await page.locator('[data-age="2-3"]').click();await page.locator('[data-game="que-necesitas-ahora"]').click();await page.locator('[data-need="⚽"]').click();await expect(page.locator('#feedback')).toContainText('necesidad');await page.locator('[data-need="🧼"]').click();await expect(page.locator('#feedback')).toContainText('solución útil');});

test('advanced logic remains absent from toddler bands',async({page})=>{await boot(page);await page.locator('[data-age="1-2"]').click();await expect(page.locator('[data-game="casitas-logicas"]')).toHaveCount(0);});
