const {test,expect}=require('@playwright/test');
async function boot(page){await page.goto('/v2/app-v200.html');await page.waitForFunction(()=>Boolean(window.MundoMimoV2RuntimeV380));}
test('v380 exposes 120 implemented games with unique handlers and no clones',async({page})=>{await boot(page);const r=await page.evaluate(()=>{const x=window.MundoMimoV2RuntimeV380,E=window.MundoMimoV2ExpansionV380;return{implemented:x.implemented,handlers:x.handlers,errors:E.errors,clones:E.cloneGroups}});expect(r.errors).toEqual([]);expect(r.clones).toEqual([]);expect(r.implemented).toHaveLength(120);expect(new Set(r.implemented).size).toBe(120);expect(new Set(r.handlers).size).toBe(120);});
test('gesture game distinguishes facial emotion cues',async({page})=>{await boot(page);await page.locator('[data-age="1-2"]').click();await page.locator('[data-game="gestos-de-mimo"]').click();await page.locator('[data-gesture="triste"]').click();await expect(page.locator('#feedback')).toContainText('ojos');await page.locator('[data-gesture="alegre"]').click();await expect(page.locator('#feedback')).toContainText('gesto');});
test('step counting enforces one-to-one movement count',async({page})=>{await boot(page);await page.locator('[data-age="2-3"]').click();await page.locator('[data-game="pasos-hasta-casa"]').click();await page.locator('[data-step]').click();await page.locator('[data-check-step]').click();await expect(page.locator('#feedback')).toContainText('faltan');await page.locator('[data-step]').click();await page.locator('[data-check-step]').click();await expect(page.locator('#feedback')).toContainText('exacto');});
test('weight ordering rejects reverse order then accepts qualitative series',async({page})=>{await boot(page);await page.locator('[data-age="4-5"]').click();await page.locator('[data-game="balanza-de-objetos"]').click();for(const id of ['maleta','libro','pluma'])await page.locator(`[data-weight="${id}"]`).click();await page.locator('[data-check-weight]').click();await expect(page.locator('#feedback')).toContainText('menos esfuerzo');for(const id of ['pluma','libro','maleta'])await page.locator(`[data-weight="${id}"]`).click();await page.locator('[data-check-weight]').click();await expect(page.locator('#feedback')).toContainText('correcto');});
test('semantic odd-one-out identifies category intruder',async({page})=>{await boot(page);await page.locator('[data-age="4-5"]').click();await page.locator('[data-game="palabra-intrusa"]').click();await page.locator('[data-word="perro"]').click();await expect(page.locator('#feedback')).toContainText('familia');await page.locator('[data-word="mesa"]').click();await expect(page.locator('#feedback')).toContainText('intrusa');});
test('shadow prediction uses opposite direction to light source',async({page})=>{await boot(page);await page.locator('[data-age="4-5"]').click();await page.locator('[data-game="sombras-al-sol"]').click();await page.locator('[data-shadow="izquierda"]').click();await expect(page.locator('#feedback')).toContainText('contrario');await page.locator('[data-shadow="derecha"]').click();await expect(page.locator('#feedback')).toContainText('opuesto');});
test('mission plan requires dependency-respecting order',async({page})=>{await boot(page);await page.locator('[data-age="5-6"]').click();await page.locator('[data-game="plan-de-dos-misiones"]').click();await page.locator('[data-mission="abre-la-caja"]').click();await page.locator('[data-mission="coge-la-llave"]').click();await page.locator('[data-check-mission]').click();await expect(page.locator('#feedback')).toContainText('antes');await page.locator('[data-mission="coge-la-llave"]').click();await page.locator('[data-mission="abre-la-caja"]').click();await page.locator('[data-check-mission]').click();await expect(page.locator('#feedback')).toContainText('desbloquea');});
test('advanced planning stays out of early developmental bands',async({page})=>{await boot(page);await page.locator('[data-age="1-2"]').click();await expect(page.locator('[data-game="plan-de-dos-misiones"]')).toHaveCount(0);await expect(page.locator('[data-game="balanza-de-objetos"]')).toHaveCount(0);await expect(page.locator('[data-game="sombras-al-sol"]')).toHaveCount(0);});