const {test,expect}=require('@playwright/test');
async function boot(page){await page.goto('/v2/app-v200.html');await page.waitForFunction(()=>Boolean(window.MundoMimoV2RuntimeV300));}

test('v300 exposes seventy-two implemented games without catalog clones',async({page})=>{await boot(page);const r=await page.evaluate(()=>{const x=window.MundoMimoV2RuntimeV300,E=window.MundoMimoV2ExpansionV300;return{implemented:x.implemented,handlers:x.handlers,games:x.allGames().map(g=>({id:g.id,mechanic:g.mechanic,area:g.area})),errors:E.errors,clones:E.cloneGroups}});expect(r.errors).toEqual([]);expect(r.clones).toEqual([]);expect(r.implemented).toHaveLength(72);expect(new Set(r.implemented).size).toBe(72);expect(new Set(r.handlers).size).toBe(72);expect(r.implemented.every(id=>r.games.some(g=>g.id===id))).toBeTruthy();});

test('day-night animal classification rejects wrong bin and completes correct grouping',async({page})=>{await boot(page);await page.locator('[data-age="3-4"]').click();await page.locator('[data-game="animales-dia-noche"]').click();await page.locator('[data-animal="0"]').click();await page.locator('[data-bin="day"]').click();await expect(page.locator('#feedback')).toContainText('día o de noche');for(const pair of [[0,'night'],[1,'day'],[2,'night'],[3,'day']]){await page.locator(`[data-animal="${pair[0]}"]`).click();await page.locator(`[data-bin="${pair[1]}"]`).click();}await expect(page.locator('#feedback')).toContainText('Clasificaste');});

test('weather clothing uses context rather than arbitrary item selection',async({page})=>{await boot(page);await page.locator('[data-age="2-3"]').click();await page.locator('[data-game="ropa-para-el-tiempo"]').click();await page.locator('[data-cloth="🩴"]').click();await expect(page.locator('#feedback')).toContainText('protege');await page.locator('[data-cloth="🧥"]').click();await expect(page.locator('#feedback')).toContainText('elección');});

test('claps-and-silences hides model and enforces silence positions',async({page})=>{await boot(page);await page.locator('[data-age="3-4"]').click();await page.locator('[data-game="palmas-y-silencios"]').click();await page.locator('[data-hide-rhythm]').click();await expect(page.locator('[data-rhythm]')).toBeHidden();await page.locator('[data-beat="🤫"]').click();await expect(page.locator('#feedback')).toContainText('cambió');await page.locator('[data-beat="👏"]').click();await page.locator('[data-beat="🤫"]').click();await page.locator('[data-beat="👏"]').click();await expect(page.locator('#feedback')).toContainText('palmas');});

test('hidden-letter search rejects lookalikes and requires all target glyphs',async({page})=>{await boot(page);await page.locator('[data-age="4-5"]').click();await page.locator('[data-game="letra-escondida"]').click();await page.locator('[data-symbol="△"]').click();await expect(page.locator('#feedback')).toContainText('no es');const targets=page.locator('[data-symbol="A"]');expect(await targets.count()).toBe(3);for(let i=0;i<3;i++)await targets.nth(i).click();await expect(page.locator('#feedback')).toContainText('todas');});

test('park turns reinforces a prosocial solution',async({page})=>{await boot(page);await page.locator('[data-age="3-4"]').click();await page.locator('[data-game="turnos-en-el-parque"]').click();await page.locator('[data-social="Empujar para llegar antes"]').click();await expect(page.locator('#feedback')).toContainText('respete');await page.locator('[data-social="Esperar turno y acordar quién va primero"]').click();await expect(page.locator('#feedback')).toContainText('respetuosa');});

test('shape bridge requires exact composed length',async({page})=>{await boot(page);await page.locator('[data-age="4-5"]').click();await page.locator('[data-game="puente-de-formas"]').click();await page.locator('[data-piece="1"]').click();await page.locator('[data-piece="3"]').click();await page.locator('[data-check-bridge]').click();await expect(page.locator('#feedback')).toContainText('exactamente 5');await page.locator('[data-piece="1"]').click();await page.locator('[data-piece="2"]').click();await page.locator('[data-check-bridge]').click();await expect(page.locator('#feedback')).toContainText('justo');});

test('advanced hidden-letter and bridge games are absent from toddler band',async({page})=>{await boot(page);await page.locator('[data-age="1-2"]').click();await expect(page.locator('[data-game="letra-escondida"]')).toHaveCount(0);await expect(page.locator('[data-game="puente-de-formas"]')).toHaveCount(0);});