const {test,expect}=require('@playwright/test');
async function boot(page){await page.goto('/v2/app-v200.html');await page.waitForFunction(()=>Boolean(window.MundoMimoV2RuntimeV390)&&typeof window.MundoMimoV2Performance?.startGame==='function'&&window.MundoMimoV2CatalogRouterBootstrap?.version===593);}
test('v390 exposes 126 implemented games with unique handlers and no clones',async({page})=>{await boot(page);const r=await page.evaluate(()=>{const x=window.MundoMimoV2RuntimeV390,E=window.MundoMimoV2ExpansionV390;return{implemented:x.implemented,handlers:x.handlers,errors:E.errors,clones:E.cloneGroups}});expect(r.errors).toEqual([]);expect(r.clones).toEqual([]);expect(r.implemented).toHaveLength(126);expect(new Set(r.implemented).size).toBe(126);expect(new Set(r.handlers).size).toBe(126);});
test('object function game links action to practical tool',async({page})=>{await boot(page);await page.locator('[data-age="2-3"]').click();await page.locator('[data-game="que-usamos-para"]').click();await page.locator('[data-tool="cuchara"]').click();await expect(page.locator('#feedback')).toContainText('sirve');await page.locator('[data-tool="peine"]').click();await expect(page.locator('#feedback')).toContainText('objeto');});
test('sound intensity game distinguishes strong and soft',async({page})=>{await boot(page);await page.locator('[data-age="2-3"]').click();await page.locator('[data-game="eco-fuerte-suave"]').click();await page.locator('[data-volume="fuerte"]').click();await expect(page.locator('#feedback')).toContainText('bajito');await page.locator('[data-volume="suave"]').click();await expect(page.locator('#feedback')).toContainText('intensidad');});
test('number series rejects distractor then accepts missing number',async({page})=>{await boot(page);await page.locator('[data-age="4-5"]').click();await page.locator('[data-game="serie-de-numeros"]').click();await page.locator('[data-number="5"]').click();await expect(page.locator('#feedback')).toContainText('aumenta');await page.locator('[data-number="3"]').click();await expect(page.locator('#feedback')).toContainText('continúa');});
test('sentence order requires syntactic sequence',async({page})=>{await boot(page);await page.locator('[data-age="5-6"]').click();await page.locator('[data-game="frase-en-orden"]').click();for(const w of ['juega','Mimo','fuera'])await page.locator(`[data-word-order="${w}"]`).click();await page.locator('[data-check-sentence]').click();await expect(page.locator('#feedback')).toContainText('Empieza');for(const w of ['Mimo','juega','fuera'])await page.locator(`[data-word-order="${w}"]`).click();await page.locator('[data-check-sentence]').click();await expect(page.locator('#feedback')).toContainText('orden claro');});
test('cause detective selects plausible causal explanation',async({page})=>{await boot(page);await page.locator('[data-age="4-5"]').click();await page.locator('[data-game="detective-de-causas"]').click();await page.locator('[data-cause="hizo-sol"]').click();await expect(page.locator('#feedback')).toContainText('producir');await page.locator('[data-cause="llovio"]').click();await expect(page.locator('#feedback')).toContainText('evidencia');});
test('copy model requires correct spatial order',async({page})=>{await boot(page);await page.locator('[data-age="4-5"]').click();await page.locator('[data-game="copia-el-modelo"]').click();for(const p of ['verde','azul','rojo'])await page.locator(`[data-piece="${p}"]`).click();await page.locator('[data-check-model]').click();await expect(page.locator('#feedback')).toContainText('izquierda');for(const p of ['rojo','azul','verde'])await page.locator(`[data-piece="${p}"]`).click();await page.locator('[data-check-model]').click();await expect(page.locator('#feedback')).toContainText('modelo');});
test('advanced v390 games stay out of early bands',async({page})=>{await boot(page);await page.locator('[data-age="1-2"]').click();for(const id of ['serie-de-numeros','frase-en-orden','detective-de-causas','copia-el-modelo'])await expect(page.locator(`[data-game="${id}"]`)).toHaveCount(0);});