const {test,expect}=require('@playwright/test');
async function boot(page){await page.goto('/v2/app-v200.html');await page.waitForFunction(()=>Boolean(window.MundoMimoV2RuntimeV370));}
test('v370 exposes 114 implemented games with unique handlers and no clones',async({page})=>{await boot(page);const r=await page.evaluate(()=>{const x=window.MundoMimoV2RuntimeV370,E=window.MundoMimoV2ExpansionV370;return{implemented:x.implemented,handlers:x.handlers,errors:E.errors,clones:E.cloneGroups}});expect(r.errors).toEqual([]);expect(r.clones).toEqual([]);expect(r.implemented).toHaveLength(114);expect(new Set(r.implemented).size).toBe(114);expect(new Set(r.handlers).size).toBe(114);});
test('follow light requires the final tracked position',async({page})=>{await boot(page);await page.locator('[data-age="1-2"]').click();await page.locator('[data-game="sigue-la-luz"]').click();await page.locator('[data-light="izq"]').click();await expect(page.locator('#feedback')).toContainText('último');await page.locator('[data-light="der"]').click();await expect(page.locator('#feedback')).toContainText('final');});
test('breakfast routine rejects reversed actions and accepts functional order',async({page})=>{await boot(page);await page.locator('[data-age="3-4"]').click();await page.locator('[data-game="ordena-el-desayuno"]').click();await page.locator('[data-breakfast="añadir-cereal"]').click();await page.locator('[data-breakfast="servir-leche"]').click();await page.locator('[data-breakfast="poner-bol"]').click();await page.locator('[data-check-breakfast]').click();await expect(page.locator('#feedback')).toContainText('primero');await page.locator('[data-breakfast="poner-bol"]').click();await page.locator('[data-breakfast="servir-leche"]').click();await page.locator('[data-breakfast="añadir-cereal"]').click();await page.locator('[data-check-breakfast]').click();await expect(page.locator('#feedback')).toContainText('ordenada');});
test('long clap echo requires the exact remembered pulse pattern',async({page})=>{await boot(page);await page.locator('[data-age="3-4"]').click();await page.locator('[data-game="eco-de-palmas-largas"]').click();await page.locator('[data-clap="largo"]').click();await page.locator('[data-clap="corto"]').click();await page.locator('[data-check-clap]').click();await expect(page.locator('#feedback')).toContainText('vuelve');await page.locator('[data-clap="corto"]').click();await page.locator('[data-clap="largo"]').click();await page.locator('[data-check-clap]').click();await expect(page.locator('#feedback')).toContainText('exacto');});
test('science change game connects the modified variable with its consequence',async({page})=>{await boot(page);await page.locator('[data-age="4-5"]').click();await page.locator('[data-game="que-cambia-si"]').click();await page.locator('[data-change="se-hiela"]').click();await expect(page.locator('#feedback')).toContainText('variable');await page.locator('[data-change="crece-hacia-luz"]').click();await expect(page.locator('#feedback')).toContainText('coherente');});
test('number neighbors completes a missing value in an ordered sequence',async({page})=>{await boot(page);await page.locator('[data-age="4-5"]').click();await page.locator('[data-game="vecinos-del-numero"]').click();await page.locator('[data-number="2"]').click();await expect(page.locator('#feedback')).toContainText('Cuenta');await page.locator('[data-number="4"]').click();await expect(page.locator('#feedback')).toContainText('vecino');});
test('story construction requires causal beginning middle and ending',async({page})=>{await boot(page);await page.locator('[data-age="5-6"]').click();await page.locator('[data-game="construye-la-historia"]').click();const cards=page.locator('[data-story]');await cards.nth(0).click();await cards.nth(1).click();await cards.nth(2).click();await page.locator('[data-check-story]').click();await expect(page.locator('#feedback')).toContainText('primero');await page.locator('[data-text="Mimo pierde su cometa"]').click();await page.locator('[data-text="la busca por el parque"]').click();await page.locator('[data-text="la encuentra en un árbol"]').click();await page.locator('[data-check-story]').click();await expect(page.locator('#feedback')).toContainText('coherente');});
test('advanced v370 narrative stays out of early bands',async({page})=>{await boot(page);await page.locator('[data-age="1-2"]').click();await expect(page.locator('[data-game="construye-la-historia"]')).toHaveCount(0);await expect(page.locator('[data-game="vecinos-del-numero"]')).toHaveCount(0);await expect(page.locator('[data-game="que-cambia-si"]')).toHaveCount(0);});