const {test,expect}=require('@playwright/test');
async function boot(page){await page.goto('/v2/app-v200.html');await page.waitForFunction(()=>Boolean(window.MundoMimoV2RuntimeV400));}
test('v400 exposes 132 implemented games with unique handlers and no clones',async({page})=>{await boot(page);const r=await page.evaluate(()=>{const x=window.MundoMimoV2RuntimeV400,E=window.MundoMimoV2ExpansionV400;return{implemented:x.implemented,handlers:x.handlers,errors:E.errors,clones:E.cloneGroups}});expect(r.errors).toEqual([]);expect(r.clones).toEqual([]);expect(r.implemented).toHaveLength(132);expect(new Set(r.implemented).size).toBe(132);expect(new Set(r.handlers).size).toBe(132);});
test('find home links familiar object to functional place',async({page})=>{await boot(page);await page.locator('[data-age="2-3"]').click();await page.locator('[data-game="encuentra-mi-casa"]').click();await page.locator('[data-home="cocina"]').click();await expect(page.locator('#feedback')).toContainText('normalmente');await page.locator('[data-home="baño"]').click();await expect(page.locator('#feedback')).toContainText('lugar habitual');});
test('turn signal rejects early action then rewards waiting',async({page})=>{await boot(page);await page.locator('[data-age="2-3"]').click();await page.locator('[data-game="semaforo-de-turnos"]').click();await page.locator('[data-turn]').click();await expect(page.locator('#feedback')).toContainText('Todavía');await expect(page.locator('[data-turn]')).toHaveText('🟢',{timeout:2500});await page.locator('[data-turn]').click();await expect(page.locator('#feedback')).toContainText('esperado');});
test('visual change comparison identifies changed element',async({page})=>{await boot(page);await page.locator('[data-age="3-4"]').click();await page.locator('[data-game="que-cambio"]').click();await page.locator('[data-change="🍎"]').click();await expect(page.locator('#feedback')).toContainText('Compara');await page.locator('[data-change="🚲"]').click();await expect(page.locator('#feedback')).toContainText('cambio');});
test('motor-word sequence requires ordered multi instruction',async({page})=>{await boot(page);await page.locator('[data-age="3-4"]').click();await page.locator('[data-game="pasos-y-palabras"]').click();for(const m of ['girar','saltar'])await page.locator(`[data-move="${m}"]`).click();await page.locator('[data-check-moves]').click();await expect(page.locator('#feedback')).toContainText('primer paso');for(const m of ['saltar','girar'])await page.locator(`[data-move="${m}"]`).click();await page.locator('[data-check-moves]').click();await expect(page.locator('#feedback')).toContainText('orden');});
test('logic clue game requires all conditions',async({page})=>{await boot(page);await page.locator('[data-age="4-5"]').click();await page.locator('[data-game="elige-la-pista"]').click();await page.locator('[data-clue="tomate"]').click();await expect(page.locator('#feedback')).toContainText('todas');await page.locator('[data-clue="manzana"]').click();await expect(page.locator('#feedback')).toContainText('pistas');});
test('creative ending chooses coherent continuation',async({page})=>{await boot(page);await page.locator('[data-age="5-6"]').click();await page.locator('[data-game="inventa-el-final"]').click();await page.locator('[data-ending="irse"]').click();await expect(page.locator('#feedback')).toContainText('continúe');await page.locator('[data-ending="pedir-ayuda"]').click();await expect(page.locator('#feedback')).toContainText('coherente');});
test('advanced v400 games stay out of early bands',async({page})=>{await boot(page);await page.locator('[data-age="1-2"]').click();for(const id of ['que-cambio','pasos-y-palabras','elige-la-pista','inventa-el-final'])await expect(page.locator(`[data-game="${id}"]`)).toHaveCount(0);});