const {test,expect}=require('@playwright/test');
async function boot(page){await page.goto('/v2/app-v200.html');await page.waitForFunction(()=>Boolean(window.MundoMimoV2RuntimeV310));}
test('v310 exposes 78 implemented games with unique handlers and no clones',async({page})=>{await boot(page);const r=await page.evaluate(()=>{const x=window.MundoMimoV2RuntimeV310,E=window.MundoMimoV2ExpansionV310;return{implemented:x.implemented,handlers:x.handlers,errors:E.errors,clones:E.cloneGroups}});expect(r.errors).toEqual([]);expect(r.clones).toEqual([]);expect(r.implemented).toHaveLength(78);expect(new Set(r.implemented).size).toBe(78);expect(new Set(r.handlers).size).toBe(78);});
test('faces links event and facial emotion',async({page})=>{await boot(page);await page.locator('[data-age="1-2"]').click();await page.locator('[data-game="caras-y-gestos"]').click();await page.locator('[data-face="😄"]').click();await expect(page.locator('#feedback')).toContainText('ocurrir');await page.locator('[data-face="😢"]').click();await expect(page.locator('#feedback')).toContainText('gesto');});
test('one-to-one distribution requires one item per child',async({page})=>{await boot(page);await page.locator('[data-age="3-4"]').click();await page.locator('[data-game="cuenta-y-reparte"]').click();const kids=page.locator('[data-child]');expect(await kids.count()).toBe(2);await kids.nth(0).click();await kids.nth(0).click();await expect(kids.nth(0)).toBeDisabled();await kids.nth(1).click();await expect(page.locator('#feedback')).toContainText('cada amigo');});
test('phoneme odd-one-out rejects same-initial distractor',async({page})=>{await boot(page);await page.locator('[data-age="4-5"]').click();await page.locator('[data-game="sonido-intruso"]').click();await page.locator('[data-word="mesa"]').click();await expect(page.locator('#feedback')).toContainText('primer sonido');await page.locator('[data-word="sol"]').click();await expect(page.locator('#feedback')).toContainText('diferente');});
test('spatial relation follows requested position',async({page})=>{await boot(page);await page.locator('[data-age="3-4"]').click();await page.locator('[data-game="mapa-de-mi-casa"]').click();await page.locator('[data-pos="encima"]').click();await expect(page.locator('#feedback')).toContainText('posición');await page.locator('[data-pos="debajo"]').click();await expect(page.locator('#feedback')).toContainText('sitio');});
test('story event drives emotion choice',async({page})=>{await boot(page);await page.locator('[data-age="4-5"]').click();await page.locator('[data-game="historia-con-emociones"]').click();await page.locator('[data-emotion="contenta"]').click();await expect(page.locator('#feedback')).toContainText('después');await page.locator('[data-emotion="triste"]').click();await expect(page.locator('#feedback')).toContainText('emoción');});
test('mini market composes exact quantity and blocks overshoot',async({page})=>{await boot(page);await page.locator('[data-age="5-6"]').click();await page.locator('[data-game="mini-mercado"]').click();await page.locator('[data-coin="3"]').click();await page.locator('[data-coin="2"]').click();await expect(page.locator('#feedback')).toContainText('pasas');await page.locator('[data-coin="1"]').click();await expect(page.locator('#feedback')).toContainText('exacta');});
test('advanced v310 games stay out of toddler bands',async({page})=>{await boot(page);await page.locator('[data-age="1-2"]').click();await expect(page.locator('[data-game="sonido-intruso"]')).toHaveCount(0);await expect(page.locator('[data-game="mini-mercado"]')).toHaveCount(0);});