const {test,expect}=require('@playwright/test');
async function boot(page){await page.goto('/v2/app-v200.html');await page.waitForFunction(()=>Boolean(window.MundoMimoV2RuntimeV410));}
test('v410 exposes 138 implemented games with unique handlers and no clones',async({page})=>{await boot(page);const r=await page.evaluate(()=>{const x=window.MundoMimoV2RuntimeV410,E=window.MundoMimoV2ExpansionV410;return{implemented:x.implemented,handlers:x.handlers,errors:E.errors,clones:E.cloneGroups}});expect(r.errors).toEqual([]);expect(r.clones).toEqual([]);expect(r.implemented).toHaveLength(138);expect(new Set(r.implemented).size).toBe(138);expect(new Set(r.handlers).size).toBe(138);});
test('sound-object association distinguishes wrong and correct referent',async({page})=>{await boot(page);await page.locator('[data-age="1-2"]').click();await page.locator('[data-game="sonido-y-objeto"]').click();await page.locator('[data-sound-object="pelota"]').click();await expect(page.locator('#feedback')).toContainText('Escucha');await page.locator('[data-sound-object="reloj"]').click();await expect(page.locator('#feedback')).toContainText('sonido');});
test('functional sorting requires category that matches object use',async({page})=>{await boot(page);await page.locator('[data-age="2-3"]').click();await page.locator('[data-game="ordena-por-uso"]').click();await page.locator('[data-use-item="cepillo"]').click();await page.locator('[data-use-cat="comer"]').click();await expect(page.locator('#feedback')).toContainText('no corresponde');await page.locator('[data-use-cat="aseo"]').click();await expect(page.locator('#feedback')).toContainText('clasificado');});
test('missing path piece restores sequence rule',async({page})=>{await boot(page);await page.locator('[data-age="3-4"]').click();await page.locator('[data-game="camino-incompleto"]').click();await page.locator('[data-path-piece="⬅️"]').click();await expect(page.locator('#feedback')).toContainText('regla');await page.locator('[data-path-piece="➡️"]').click();await expect(page.locator('#feedback')).toContainText('coherente');});
test('syllable train enforces spoken order',async({page})=>{await boot(page);await page.locator('[data-age="4-5"]').click();await page.locator('[data-game="tren-de-silabas"]').click();await page.locator('[data-syllable="sa"]').click();await page.locator('[data-syllable="ca"]').click();await page.locator('[data-check-syllables]').click();await expect(page.locator('#feedback')).toContainText('Prueba');await page.locator('[data-syllable="ca"]').click();await page.locator('[data-syllable="sa"]').click();await page.locator('[data-check-syllables]').click();await expect(page.locator('#feedback')).toContainText('palabra');});
test('morning plan respects task dependencies',async({page})=>{await boot(page);await page.locator('[data-age="5-6"]').click();await page.locator('[data-game="plan-de-manana"]').click();for(const x of ['salir','vestirse','desayunar'])await page.locator(`[data-plan-step="${x}"]`).click();await page.locator('[data-check-plan]').click();await expect(page.locator('#feedback')).toContainText('antes');for(const x of ['vestirse','desayunar','salir'])await page.locator(`[data-plan-step="${x}"]`).click();await page.locator('[data-check-plan]').click();await expect(page.locator('#feedback')).toContainText('orden');});
test('balance composition requires exact target',async({page})=>{await boot(page);await page.locator('[data-age="5-6"]').click();await page.locator('[data-game="balanza-de-puntos"]').click();await page.locator('[data-balance="1"]').click();await expect(page.locator('#feedback')).toContainText('exactamente');await page.locator('[data-balance="0"]').click();await expect(page.locator('#feedback')).toContainText('equilibrada');});
test('advanced v410 games stay out of early bands',async({page})=>{await boot(page);await page.locator('[data-age="1-2"]').click();for(const id of ['camino-incompleto','tren-de-silabas','plan-de-manana','balanza-de-puntos'])await expect(page.locator(`[data-game="${id}"]`)).toHaveCount(0);});