const {test,expect}=require('@playwright/test');
const BASE='http://127.0.0.1:4173/app-v70.html';
async function fresh(page){await page.goto(BASE,{waitUntil:'domcontentloaded'});}
async function ready(page,age=3){await page.goto(BASE,{waitUntil:'domcontentloaded'});await page.evaluate(a=>localStorage.setItem('mimo70',JSON.stringify({age:a,sessions:0,rounds:0,stars:0,daily:0,dailyDate:new Date().toISOString().slice(0,10),skills:{}})),age);await page.reload({waitUntil:'domcontentloaded'});await expect(page.locator('#home')).toHaveClass(/on/)}
function errs(page){const a=[];page.on('pageerror',e=>a.push(e.message));return a}
for(const age of ['1','3','5'])test(`familia puede elegir franja ${age}`,async({page})=>{await fresh(page);const b=page.locator(`[data-age="${age}"]`);await expect(b).toBeVisible();await b.click();await expect(page.locator('#home')).toHaveClass(/on/)});
test('familia ve promesa sin anuncios ni compras infantiles',async({page})=>{await ready(page);await expect(page.locator('.trust')).toContainText('Sin anuncios');await expect(page.locator('.trust')).toContainText('sin compras infantiles')});
test('niño inicia aventura de hoy',async({page})=>{await ready(page);await page.locator('[data-action="today"]').click();await expect(page.locator('#game')).toHaveClass(/on/)});
test('zona familiar queda detrás de control parental',async({page})=>{await ready(page);await page.locator('[data-action="parent"]').first().click();await expect(page.locator('#parentGate')).toHaveClass(/on/)});
for(const world of ['forest','lagoon','village','mountain'])test(`niño abre mundo ${world}`,async({page})=>{await ready(page);await page.locator(`[data-world="${world}"]`).first().click();await expect(page.locator('#world')).toHaveClass(/on/);await expect(page.locator('#activityGrid button')).toHaveCount(6)});
for(const [world,game] of [['forest','animals'],['forest','memory'],['lagoon','count'],['lagoon','shapes'],['village','emotions'],['village','paint'],['mountain','letters'],['mountain','logic']])test(`niño abre ${world}/${game}`,async({page})=>{await ready(page,5);await page.locator(`[data-world="${world}"]`).first().click();await page.locator(`#activityGrid [data-game="${game}"]`).click();await expect(page.locator('#game')).toHaveClass(/on/);await expect(page.locator('#playfield')).toBeVisible()});
for(const width of [320,375,390,430])test(`Mundo Mimo cabe a ${width}px`,async({page})=>{await page.setViewportSize({width,height:760});await ready(page);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth+2)).toBeTruthy()});
test('niño puede volver del mundo al inicio',async({page})=>{await ready(page);await page.locator('[data-world="forest"]').first().click();await page.locator('#world [data-action="home"]').click();await expect(page.locator('#home')).toHaveClass(/on/)});
test('niño puede explorar dibujo libre',async({page})=>{await ready(page);await page.locator('.freeGrid [data-game="paint"]').click();await expect(page.locator('#game')).toHaveClass(/on/)});
test('niño puede explorar música libre',async({page})=>{await ready(page);await page.locator('.freeGrid [data-game="music"]').click();await expect(page.locator('#game')).toHaveClass(/on/)});
test('navegación inferior ofrece cuatro destinos',async({page})=>{await ready(page);await expect(page.locator('#bottomBar button')).toHaveCount(4)});
test('targets principales son de al menos 44px',async({page})=>{await ready(page);const n=await page.locator('#home button:visible,#bottomBar button:visible').evaluateAll(ns=>ns.filter(x=>{const r=x.getBoundingClientRect();return r.width<44||r.height<44}).length);expect(n).toBe(0)});
test('reduced motion conserva experiencia',async({page})=>{await page.emulateMedia({reducedMotion:'reduce'});await ready(page);await expect(page.locator('#home')).toHaveClass(/on/)});
test('recarga conserva edad elegida',async({page})=>{await ready(page,5);await page.reload({waitUntil:'domcontentloaded'});await expect(page.locator('#homeAge')).toContainText('5–6')});
test('recorrido infantil básico no lanza pageerror',async({page})=>{const e=errs(page);await ready(page);await page.locator('[data-world="lagoon"]').first().click();await page.locator('#activityGrid [data-game="count"]').click();expect(e).toEqual([])});
